/* Scoop Sense — filtering, sorting, and rendering.
 *
 * Loads AFTER data/products.js on every scripted page. Reads the globals
 * PRODUCTS and FEATURED_IDS; defines nothing else on window.
 *
 * Renderers, by page:
 *   hub.html      — #sc-products shop-style card grid + toolbar filters
 *   index.html    — #sc-preview-body database preview + #sc-starts picks
 *   compare.html  — #sc-compare-body sortable table
 *
 * Product detail pages are static files in products/ generated by
 * scripts/build-product-pages.js — regenerate after data changes.
 */

(function () {
  "use strict";

  // Category landing pages declare themselves via <body data-category="...">;
  // the dataset (grid AND compare rows) is then locked to that category.
  var PAGE_CATEGORY = document.body.getAttribute("data-category") || null;

  var state = {
    search: "",
    category: PAGE_CATEGORY || "all",
    caffeine: "all",
    brand: "all",
    stimFreeOnly: false,
    sort: "name"
  };

  // Products predate the category field; missing means pre-workout.
  function categoryOf(p) {
    return p.category || "pre-workout";
  }

  function cfgOf(p) {
    return CATEGORY_CONFIG[categoryOf(p)] || CATEGORY_CONFIG["pre-workout"];
  }

  function categoryLabelOf(p) {
    var c = categoryOf(p);
    if (CATEGORY_CONFIG[c]) return CATEGORY_CONFIG[c].label;
    return c.charAt(0).toUpperCase() + c.slice(1);
  }

  /* ---------------------------------------------------------------------
   * Helpers
   * ------------------------------------------------------------------- */

  function esc(value) {
    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  // Caffeine bucket: matches the hub's caffeine <select> values.
  function bucketOf(p) {
    if (p.caffeineMg === 0) return "none";
    if (p.caffeineMg < 150) return "low";
    if (p.caffeineMg < 250) return "moderate";
    return "high";
  }

  function stimLabelOf(p) {
    var bucket = bucketOf(p);
    if (bucket === "none") return "Stim-free";
    if (bucket === "low") return "Low stim";
    if (bucket === "moderate") return "Moderate stim";
    return "High stim";
  }

  // "8 g" -> 8000, "350 mg" -> 350, unparseable -> null.
  function parseDoseMg(dose) {
    var m = /([\d.]+)\s*(mg|g)\b/i.exec(dose || "");
    if (!m) return null;
    var n = parseFloat(m[1]);
    return m[2].toLowerCase() === "g" ? n * 1000 : n;
  }

  function findIngredient(p, re) {
    for (var i = 0; i < p.keyIngredients.length; i++) {
      if (re.test(p.keyIngredients[i].name)) return p.keyIngredients[i];
    }
    return null;
  }

  // Citrulline: distinguishes malate from pure L-citrulline — the two are
  // not interchangeable gram for gram.
  function citrullineOf(p) {
    var ing = findIngredient(p, /citrulline/i);
    if (!ing) return null;
    return { dose: ing.dose, form: /malate/i.test(ing.name) ? "malate" : "" };
  }

  function betaAlanineOf(p) {
    var ing = findIngredient(p, /beta[- ]alanine/i);
    return ing ? ing.dose : null;
  }

  function hasBlend(p) {
    if (p.badges.indexOf("Proprietary Blend") !== -1) return true;
    return !!findIngredient(p, /blend/i);
  }

  function isDisclosed(p) {
    return p.badges.indexOf("Fully Disclosed Label") !== -1;
  }

  function matchesSearch(p, term) {
    if (!term) return true;
    var haystack = [p.name, p.brand]
      .concat(p.keyIngredients.map(function (ing) { return ing.name; }))
      .join(" ")
      .toLowerCase();
    return haystack.indexOf(term) !== -1;
  }

  function applyFilters() {
    var term = state.search.trim().toLowerCase();

    var results = PRODUCTS.filter(function (p) {
      if (!matchesSearch(p, term)) return false;
      if (state.category !== "all" && categoryOf(p) !== state.category) return false;
      if (state.caffeine !== "all" && bucketOf(p) !== state.caffeine) return false;
      if (state.brand !== "all" && p.brand !== state.brand) return false;
      if (state.stimFreeOnly && p.stimFree !== true) return false;
      return true;
    });

    results.sort(function (a, b) {
      if (state.sort === "caffeine-asc") return a.caffeineMg - b.caffeineMg;
      if (state.sort === "caffeine-desc") return b.caffeineMg - a.caffeineMg;
      return a.name.localeCompare(b.name) || a.brand.localeCompare(b.brand);
    });

    return results;
  }

  /* ---------------------------------------------------------------------
   * Shared cell fragments
   * ------------------------------------------------------------------- */

  function citrullineHTML(p) {
    var cit = citrullineOf(p);
    if (!cit) return '<span class="sc-dim">—</span>';
    return esc(cit.dose) + (cit.form ? " <small>" + esc(cit.form) + "</small>" : "");
  }

  function betaHTML(p) {
    var dose = betaAlanineOf(p);
    return dose ? esc(dose) : '<span class="sc-dim">—</span>';
  }

  function blendHTML(p) {
    return hasBlend(p) ? "Yes" : '<span class="sc-dim">No</span>';
  }

  // "$" | "$$" | "$$$" -> plain-English cost-per-serving tier, with the basis
  // for the judgment exposed as a tooltip.
  var PRICE_TIPS = {
    Budget: "Estimated cost per full serving sits in the lowest third of this database — roughly $1.10 or less at the time of the last label check.",
    "Mid-range": "Estimated cost per full serving sits in the middle third of this database — roughly $1.10–$1.90 at the time of the last label check.",
    Premium: "Estimated cost per full serving sits in the highest third of this database — roughly $1.90 or more at the time of the last label check."
  };

  function priceWordOf(p) {
    return p.priceRange === "$" ? "Budget" : p.priceRange === "$$" ? "Mid-range" : "Premium";
  }

  function priceWordHTML(p) {
    var w = priceWordOf(p);
    return '<span title="' + esc(PRICE_TIPS[w]) + '">' + w + "</span>";
  }

  /* Config fact-key resolver — see the key grammar comment in
   * js/categories.js. Returns an HTML cell fragment; missing -> em-dash. */

  var DASH = '<span class="sc-dim">—</span>';

  function metricOf(p, key) {
    if (!p.metrics) return null;
    var v = p.metrics[key];
    return v === undefined || v === null || v === "" ? null : v;
  }

  function factOf(p, key) {
    if (key === "caffeineMg") {
      return p.caffeineMg === 0 ? "0 mg" : esc(p.caffeineMg) + " mg";
    }
    if (key === "servings") return esc(p.servings);
    if (key === "blend") return blendHTML(p);
    if (key === "stim") return esc(stimLabelOf(p));
    if (key === "price") return priceWordHTML(p);
    if (key === "protPct") {
      var pg = metricOf(p, "proteinG"), sg = metricOf(p, "servingG");
      if (!pg || !sg) return DASH;
      return Math.round((pg / sg) * 100) + "%";
    }
    if (key.indexOf("ing:") === 0) {
      var pattern = key.slice(4);
      if (/citrulline/.test(pattern)) return citrullineHTML(p);
      var ing = findIngredient(p, new RegExp(pattern, "i"));
      return ing ? esc(ing.dose) : DASH;
    }
    if (key.indexOf("m:") === 0) {
      var parts = key.split(":");
      var v = metricOf(p, parts[1]);
      if (v === null) return DASH;
      return esc(v) + (parts[2] ? " " + parts[2] : "");
    }
    return DASH;
  }

  // Numeric twin for sorting; missing -> -1 so gaps sink to the bottom.
  function factSortValue(p, key) {
    if (key === "name") return (p.brand + " " + p.name).toLowerCase();
    if (key === "caffeineMg") return p.caffeineMg;
    if (key === "servings") return p.servings;
    if (key === "blend") return hasBlend(p) ? 1 : 0;
    if (key === "stim") return p.caffeineMg;
    if (key === "price") return p.priceRange === "$" ? 1 : p.priceRange === "$$" ? 2 : 3;
    if (key === "protPct") {
      var pg = metricOf(p, "proteinG"), sg = metricOf(p, "servingG");
      return pg && sg ? pg / sg : -1;
    }
    if (key.indexOf("ing:") === 0) {
      var ing = findIngredient(p, new RegExp(key.slice(4), "i"));
      return ing ? (parseDoseMg(ing.dose) || -1) : -1;
    }
    if (key.indexOf("m:") === 0) {
      var v = metricOf(p, key.split(":")[1]);
      return typeof v === "number" ? v : -1;
    }
    return 0;
  }

  function productLinkCell(p) {
    return '<a href="products/' + esc(p.id) + '.html">' +
      '<span class="sc-cell-brand">' + esc(p.brand) + "</span>" +
      '<span class="sc-cell-name">' + esc(p.name) + "</span></a>";
  }

  /* ---------------------------------------------------------------------
   * Product tiles (hub) — shop-style cards. The card links to the static
   * product page (products/<id>.html); the CTA row holds the two actions.
   * All fields escaped before interpolation.
   *
   * Tiles render p.imageUrl when present (affiliate-approved imagery
   * only); otherwise a generic stylized tub — never real packaging.
   * ------------------------------------------------------------------- */

  function monogramOf(p) {
    var words = (p.brand || "?").split(/\s+/);
    var mono = words[0].charAt(0) + (words[1] ? words[1].charAt(0) : "");
    return mono.toUpperCase();
  }

  // Mirrors tubSVG in scripts/build-product-pages.js — keep in sync.
  function tubSVG(p) {
    var accent = p.accentColor || "#4A4237";
    return '<svg viewBox="0 0 200 240" xmlns="http://www.w3.org/2000/svg">' +
      '<rect x="34" y="6" width="132" height="34" rx="10" fill="#0B0D10" stroke="#333A44"/>' +
      '<rect x="24" y="44" width="152" height="186" rx="14" fill="#191D23" stroke="#333A44"/>' +
      '<rect x="38" y="78" width="124" height="118" rx="6" fill="#F2EDE3"/>' +
      '<rect x="38" y="78" width="124" height="14" rx="6" fill="' + esc(accent) + '"/>' +
      '<text x="100" y="150" text-anchor="middle" font-family="Barlow Condensed, Arial Narrow, sans-serif" ' +
        'font-size="44" font-weight="700" fill="#17140F" letter-spacing="2">' + esc(monogramOf(p)) + "</text>" +
      '<rect x="56" y="166" width="88" height="3" fill="#17140F" opacity="0.75"/>' +
      '<rect x="56" y="176" width="88" height="2" fill="#17140F" opacity="0.3"/>' +
      '<rect x="56" y="184" width="62" height="2" fill="#17140F" opacity="0.3"/>' +
    "</svg>";
  }

  // Plain-English explanations surfaced as native tooltips on the tag chips.
  var STIM_TIPS = {
    none: "0 mg caffeine per serving. Stim-free is not effect-free — the other ingredients are still active.",
    low: "Under 150 mg caffeine per full serving — less than two small cups of coffee.",
    moderate: "150–249 mg caffeine per full serving — roughly two small cups of coffee.",
    high: "250 mg or more caffeine per full serving. The FDA cites about 400 mg per day for healthy adults."
  };
  var DISCLOSED_TIP = "Every active ingredient and its dosage is individually listed on the label. No proprietary blends.";
  var BLEND_TIP = "One or more combined blend totals hide the individual ingredient amounts inside.";
  var TESTED_TIP = "Certified by an independent banned-substance testing program (NSF Certified for Sport, Informed Sport, or Informed Choice), per the label or brand page.";

  // Stim tag rule: pre-workout tiles always carry one; every other category
  // shows one only when the formula is actually caffeinated — a "Stim-Free"
  // chip on a protein shelf is noise, but caffeine anywhere deserves a flag.
  // (The config stimBadges flag gates the caffeine FILTERS on landing pages,
  // not this tag.)
  function showsStimTag(p) {
    return categoryOf(p) === "pre-workout" || p.caffeineMg > 0;
  }

  function tagsHTML(p) {
    var tags = [];
    var bucket = bucketOf(p);
    if (showsStimTag(p)) {
      var stimClass = "sc-tag";
      if (bucket === "high") stimClass += " sc-tag-caution";
      if (bucket === "none") stimClass += " sc-tag-calm";
      tags.push('<span class="' + stimClass + '" title="' + esc(STIM_TIPS[bucket]) + '">' + esc(stimLabelOf(p)) + "</span>");
    }
    if (hasBlend(p)) {
      tags.push('<span class="sc-tag sc-tag-caution" title="' + esc(BLEND_TIP) + '">Proprietary blend</span>');
    } else if (isDisclosed(p)) {
      tags.push('<span class="sc-tag" title="' + esc(DISCLOSED_TIP) + '">Label fully disclosed</span>');
    }
    if (p.badges.indexOf("Third-Party Tested") !== -1) {
      tags.push('<span class="sc-tag sc-tag-calm" title="' + esc(TESTED_TIP) + '">Third-party tested</span>');
    }
    return tags.join("");
  }

  function tileFactHTML(label, valueHTML) {
    return '<span class="sc-tile-fact">' +
      '<span class="sc-tile-fact-label">' + label + "</span>" +
      '<span class="sc-tile-fact-value">' + valueHTML + "</span>" +
    "</span>";
  }

  function tileHTML(p) {
    var accent = p.accentColor ? ' style="--sc-p-accent:' + esc(p.accentColor) + '"' : "";
    var page = "products/" + esc(p.id) + ".html";

    return '<article class="sc-tile" id="p-' + esc(p.id) + '"' + accent + ">" +
      '<a class="sc-tile-link" href="' + page + '" ' +
        'aria-label="Full label breakdown: ' + esc(p.brand + " " + p.name) + '">' +
        '<span class="sc-tile-art" aria-hidden="true">' +
          (p.imageUrl ? '<img src="' + esc(p.imageUrl) + '" alt="">' : tubSVG(p)) +
        "</span>" +
        '<span class="sc-tile-top">' +
          '<span class="sc-tile-brand">' + esc(p.brand) + "</span>" +
          '<span class="sc-tile-name">' + esc(p.name) + "</span>" +
        "</span>" +
        '<span class="sc-tile-tags">' + tagsHTML(p) + "</span>" +
        '<span class="sc-tile-facts">' +
          cfgOf(p).tileFacts.map(function (f) {
            return tileFactHTML(esc(f.label), factOf(p, f.key));
          }).join("") +
        "</span>" +
        '<span class="sc-tile-foot">' +
          "<span>" + esc(p.servings) + " servings · " + priceWordHTML(p) + "</span>" +
        "</span>" +
      "</a>" +
      '<div class="sc-tile-ctas">' +
        '<a class="sc-btn sc-btn-primary" href="' + page + '">Full breakdown</a>' +
        '<a class="sc-btn sc-btn-secondary" href="' + esc(p.affiliateUrl) + '" ' +
          'target="_blank" rel="sponsored nofollow noopener" ' +
          'aria-label="View current price for ' + esc(p.brand + " " + p.name) +
          ' on Amazon (affiliate link)">View current price <span class="sc-ext" aria-hidden="true">&#8599;</span></a>' +
        saveBtnHTML(p) +
      "</div>" +
    "</article>";
  }

  /* ---------------------------------------------------------------------
   * Hub
   * ------------------------------------------------------------------- */

  function renderHub() {
    var list = document.getElementById("sc-products");
    var count = document.getElementById("sc-count");
    var empty = document.getElementById("sc-empty");
    var results = applyFilters();

    list.innerHTML = results.map(tileHTML).join("");

    if (count) {
      var pool = PAGE_CATEGORY
        ? PRODUCTS.filter(function (p) { return categoryOf(p) === PAGE_CATEGORY; }).length
        : PRODUCTS.length;
      count.textContent = "Showing " + results.length + " of " + pool + " products";
    }
    if (empty) {
      empty.hidden = results.length !== 0;
    }

    // Fresh tiles from a filter change reveal as they enter the viewport.
    if (revealObserver) initReveal();
  }

  function populateBrands(select) {
    var brands = [];
    for (var i = 0; i < PRODUCTS.length; i++) {
      if (PAGE_CATEGORY && categoryOf(PRODUCTS[i]) !== PAGE_CATEGORY) continue;
      if (brands.indexOf(PRODUCTS[i].brand) === -1) brands.push(PRODUCTS[i].brand);
    }
    brands.sort(function (a, b) { return a.localeCompare(b); });
    for (var j = 0; j < brands.length; j++) {
      var option = document.createElement("option");
      option.value = brands[j];
      option.textContent = brands[j];
      select.appendChild(option);
    }
  }

  function populateCategories(select) {
    var cats = [];
    for (var i = 0; i < PRODUCTS.length; i++) {
      var c = categoryOf(PRODUCTS[i]);
      if (cats.indexOf(c) === -1) cats.push(c);
    }
    if (cats.length < 2) { select.hidden = true; return; }
    cats.sort();
    for (var j = 0; j < cats.length; j++) {
      var option = document.createElement("option");
      option.value = cats[j];
      option.textContent = CATEGORY_CONFIG[cats[j]]
        ? CATEGORY_CONFIG[cats[j]].label
        : cats[j].charAt(0).toUpperCase() + cats[j].slice(1);
      select.appendChild(option);
    }
  }

  function wireFilters() {
    var search = document.getElementById("sc-search");
    var category = document.getElementById("sc-category");
    var caffeine = document.getElementById("sc-caffeine");
    var brand = document.getElementById("sc-brand");
    var stimFree = document.getElementById("sc-stimfree");
    var sort = document.getElementById("sc-sort");
    var clear = document.getElementById("sc-clear");
    var filtersBtn = document.getElementById("sc-filters-btn");
    var filtersPanel = document.getElementById("sc-filters");

    if (search) {
      search.addEventListener("input", function () {
        state.search = search.value;
        renderHub();
      });
    }

    if (category) {
      populateCategories(category);
      // Deep link: hub.html#cat-<slug> preselects a category.
      var mcat = /^#cat-([a-z-]+)$/.exec(location.hash);
      if (mcat && !PAGE_CATEGORY && CATEGORY_CONFIG[mcat[1]]) {
        state.category = mcat[1];
        category.value = mcat[1];
      }
      category.addEventListener("change", function () {
        state.category = category.value;
        renderHub();
      });
    }

    if (caffeine) {
      caffeine.addEventListener("change", function () {
        state.caffeine = caffeine.value;
        renderHub();
      });
    }

    if (brand) {
      populateBrands(brand);
      brand.addEventListener("change", function () {
        state.brand = brand.value;
        renderHub();
      });
    }

    if (stimFree) {
      stimFree.addEventListener("change", function () {
        state.stimFreeOnly = stimFree.checked;
        renderHub();
      });
    }

    if (sort) {
      sort.addEventListener("change", function () {
        state.sort = sort.value;
        renderHub();
      });
    }

    if (clear) {
      clear.addEventListener("click", function () {
        state.search = "";
        state.category = PAGE_CATEGORY || "all";
        state.caffeine = "all";
        state.brand = "all";
        state.stimFreeOnly = false;
        state.sort = "name";
        if (search) search.value = "";
        if (category) category.value = "all";
        if (caffeine) caffeine.value = "all";
        if (brand) brand.value = "all";
        if (stimFree) stimFree.checked = false;
        if (sort) sort.value = "name";
        renderHub();
      });
    }

    if (filtersBtn && filtersPanel) {
      filtersBtn.addEventListener("click", function () {
        var open = filtersPanel.classList.toggle("sc-open");
        filtersBtn.setAttribute("aria-expanded", open ? "true" : "false");
      });
    }
  }

  // Legacy deep links (hub.html#p-<id>) now live at products/<id>.html.
  function redirectLegacyHash() {
    var m = /^#p-([a-z0-9-]+)$/.exec(location.hash);
    if (!m || !byId(m[1])) return;
    location.replace("products/" + m[1] + ".html");
  }

  /* ---------------------------------------------------------------------
   * Homepage: database preview + places to start
   * ------------------------------------------------------------------- */

  var PREVIEW_IDS = [
    "ryse-godzilla", "legion-pulse", "kaged-pre-kaged",
    "transparent-labs-bulk", "c4-original", "legion-pulse-stim-free"
  ];

  function byId(id) {
    return PRODUCTS.find(function (p) { return p.id === id; });
  }

  function previewRowHTML(p) {
    return "<tr>" +
      "<td>" + productLinkCell(p) + "</td>" +
      '<td class="sc-num">' + esc(p.caffeineMg) + " mg</td>" +
      '<td class="sc-num">' + citrullineHTML(p) + "</td>" +
      '<td class="sc-num">' + betaHTML(p) + "</td>" +
      "<td>" + blendHTML(p) + "</td>" +
      "<td>" + esc(stimLabelOf(p)) + "</td>" +
    "</tr>";
  }

  function renderPreview() {
    var body = document.getElementById("sc-preview-body");
    body.innerHTML = PREVIEW_IDS.map(byId).filter(Boolean).map(previewRowHTML).join("");
  }

  // Editorial framing for the FEATURED_IDS picks; stats come from the data.
  var START_META = {
    "ryse-godzilla": {
      label: "Highest caffeine on file",
      why: "Close to the FDA's 400 mg daily reference amount in a single serving."
    },
    "transparent-labs-bulk": {
      label: "Disclosed formula at studied doses",
      why: "Citrulline, beta-alanine, and betaine all at commonly studied amounts."
    },
    "legion-pulse-stim-free": {
      label: "Stim-free option",
      why: "Pump and focus ingredients at full doses, without caffeine."
    }
  };

  function renderStarts() {
    var target = document.getElementById("sc-starts");
    target.innerHTML = FEATURED_IDS.map(function (id) {
      var p = byId(id);
      var meta = START_META[id];
      if (!p || !meta) return "";
      return '<div class="sc-start">' +
        '<p class="sc-start-label">' + esc(meta.label) + "</p>" +
        '<p class="sc-start-body"><strong>' + esc(p.brand + " " + p.name) + "</strong> · " +
          esc(p.caffeineMg) + " mg caffeine" +
          '<span class="sc-start-why">' + esc(meta.why) + "</span></p>" +
        '<a class="sc-action-link" href="products/' + esc(p.id) + '.html">Label breakdown</a>' +
      "</div>";
    }).join("");
  }

  /* ---------------------------------------------------------------------
   * Compare page — sortable full-database table
   * ------------------------------------------------------------------- */

  var compareState = { key: "name", dir: 1 };

  // Compare tables are per-category: the page's data-category picks the
  // column set from CATEGORY_CONFIG and locks the row set. The <thead> is
  // built here so category pages ship an empty table shell.
  function compareCfg() {
    return CATEGORY_CONFIG[PAGE_CATEGORY] || CATEGORY_CONFIG["pre-workout"];
  }

  function buildCompareHead() {
    var head = document.querySelector("#sc-compare thead");
    var cols = compareCfg().compareCols;
    var cells = ['<th scope="col" data-sortkey="name">' +
      '<button type="button" class="sc-sort-btn">Product</button></th>'];
    for (var i = 0; i < cols.length; i++) {
      var c = cols[i];
      cells.push('<th scope="col"' + (c.num ? ' class="sc-num"' : "") +
        (c.sortable ? ' data-sortkey="' + esc(c.key) + '"' : "") + ">" +
        (c.sortable
          ? '<button type="button" class="sc-sort-btn">' + esc(c.label) + "</button>"
          : esc(c.label)) +
      "</th>");
    }
    head.innerHTML = "<tr>" + cells.join("") + "</tr>";
  }

  function compareRowHTML(p) {
    var cols = compareCfg().compareCols;
    var cells = ["<td>" + productLinkCell(p) + "</td>"];
    for (var i = 0; i < cols.length; i++) {
      cells.push("<td" + (cols[i].num ? ' class="sc-num"' : "") + ">" +
        factOf(p, cols[i].key) + "</td>");
    }
    return "<tr>" + cells.join("") + "</tr>";
  }

  function renderCompare() {
    var body = document.getElementById("sc-compare-body");
    var rows = PRODUCTS.filter(function (p) {
      return !PAGE_CATEGORY || categoryOf(p) === PAGE_CATEGORY;
    }).sort(function (a, b) {
      var va = factSortValue(a, compareState.key);
      var vb = factSortValue(b, compareState.key);
      if (va < vb) return -1 * compareState.dir;
      if (va > vb) return 1 * compareState.dir;
      return 0;
    });
    body.innerHTML = rows.map(compareRowHTML).join("");

    var headers = document.querySelectorAll("#sc-compare th[data-sortkey]");
    for (var i = 0; i < headers.length; i++) {
      var key = headers[i].getAttribute("data-sortkey");
      if (key === compareState.key) {
        headers[i].setAttribute("aria-sort",
          compareState.dir === 1 ? "ascending" : "descending");
      } else {
        headers[i].removeAttribute("aria-sort");
      }
    }
  }

  function wireCompare() {
    var head = document.querySelector("#sc-compare thead");
    buildCompareHead();
    head.addEventListener("click", function (event) {
      var btn = event.target.closest(".sc-sort-btn");
      if (!btn) return;
      var th = btn.closest("th[data-sortkey]");
      if (!th) return;
      var key = th.getAttribute("data-sortkey");
      if (compareState.key === key) {
        compareState.dir = -compareState.dir;
      } else {
        compareState.key = key;
        // Numbers read best high-to-low on first click; names A-Z.
        compareState.dir = key === "name" ? 1 : -1;
      }
      renderCompare();
    });
  }

  /* ---------------------------------------------------------------------
   * Structured data — ItemList of the full database (hub page only).
   * ------------------------------------------------------------------- */

  function injectCatalogLD() {
    var ld = {
      "@context": "https://schema.org",
      "@type": "ItemList",
      "name": PAGE_CATEGORY && CATEGORY_CONFIG[PAGE_CATEGORY]
        ? CATEGORY_CONFIG[PAGE_CATEGORY].label + " label database"
        : "Supplement label database",
      "numberOfItems": undefined,
      "itemListElement": PRODUCTS.filter(function (p) {
        return !PAGE_CATEGORY || categoryOf(p) === PAGE_CATEGORY;
      }).map(function (p, i) {
        return {
          "@type": "ListItem",
          "position": i + 1,
          "name": p.brand + " " + p.name,
          "url": "products/" + p.id + ".html"
        };
      })
    };
    var script = document.createElement("script");
    script.type = "application/ld+json";
    script.textContent = JSON.stringify(ld);
    document.head.appendChild(script);
  }

  /* ---------------------------------------------------------------------
   * Scroll reveal — subtle rise-in as sections enter the viewport.
   * Runs on every page (product pages load this file without data).
   * Elements are only hidden AFTER the observer exists, so no-JS and
   * old browsers always see the full page.
   * ------------------------------------------------------------------- */

  var revealObserver = null;

  // Above-the-fold blocks (hero, hub intro, PDP top, buybox) animate on
  // page load via CSS instead — never list them here or they double-fire.
  var REVEAL_TARGETS = [
    ".sc-section-head", ".sc-table-scroll", ".sc-table-note",
    ".sc-method-steps li", ".sc-annotated", ".sc-start", ".sc-faq details",
    ".sc-safety", ".sc-cta-band .sc-container", ".sc-tile", ".sc-facts",
    ".sc-related-card", ".sc-pdp-h2", ".sc-pdp-reviews-note",
    ".sc-verify-note", ".sc-footer-grid"
  ].join(", ");

  function initReveal() {
    if (!("IntersectionObserver" in window)) return;

    if (!revealObserver) {
      revealObserver = new IntersectionObserver(function (entries) {
        for (var i = 0; i < entries.length; i++) {
          if (entries[i].isIntersecting) {
            entries[i].target.classList.add("sc-in");
            revealObserver.unobserve(entries[i].target);
          }
        }
      }, { rootMargin: "0px 0px -14% 0px", threshold: 0.15 });
    }

    var els = document.querySelectorAll(REVEAL_TARGETS);
    for (var j = 0; j < els.length; j++) {
      if (els[j].dataset.reveal) continue;
      els[j].dataset.reveal = "1";
      els[j].classList.add("sc-reveal");
      revealObserver.observe(els[j]);
    }
  }

  /* ---------------------------------------------------------------------
   * Shortlist — "save to compare". Deliberately NOT a cart: nothing can be
   * bought on this site. It's a reading list for side-by-side label
   * comparison, stored only in the visitor's browser (localStorage).
   * Works on data-less product pages too (only needs the id).
   * ------------------------------------------------------------------- */

  var SAVE_KEY = "sc-shortlist";

  function getSaved() {
    try {
      var a = JSON.parse(localStorage.getItem(SAVE_KEY) || "[]");
      return Array.isArray(a) ? a : [];
    } catch (e) { return []; }
  }

  function storeSaved(ids) {
    try { localStorage.setItem(SAVE_KEY, JSON.stringify(ids)); } catch (e) {}
    syncSaveUI();
  }

  function toggleSaved(id) {
    var ids = getSaved();
    var i = ids.indexOf(id);
    if (i === -1) ids.push(id); else ids.splice(i, 1);
    storeSaved(ids);
  }

  function saveBtnHTML(p) {
    var saved = getSaved().indexOf(p.id) !== -1;
    return '<button type="button" class="sc-save-btn" data-save-id="' + esc(p.id) + '" aria-pressed="' + saved + '">' +
      '<span class="sc-save-icon" aria-hidden="true"></span>' +
      '<span class="sc-save-text">' + (saved ? "Saved" : "Save to compare") + "</span>" +
    "</button>";
  }

  // Refresh every save toggle, nav counter, and the saved page (if open).
  function syncSaveUI() {
    var ids = getSaved();
    var btns = document.querySelectorAll("[data-save-id]");
    for (var i = 0; i < btns.length; i++) {
      var saved = ids.indexOf(btns[i].getAttribute("data-save-id")) !== -1;
      btns[i].setAttribute("aria-pressed", saved ? "true" : "false");
      var t = btns[i].querySelector(".sc-save-text");
      if (t) t.textContent = saved ? "Saved" : "Save to compare";
    }
    var counts = document.querySelectorAll(".sc-saved-count");
    for (var j = 0; j < counts.length; j++) {
      counts[j].textContent = ids.length ? "(" + ids.length + ")" : "";
    }
    var savedRoot = document.getElementById("sc-saved-root");
    if (savedRoot && typeof PRODUCTS !== "undefined") renderSavedPage(savedRoot);
  }

  function savedRowHTML(label, cells) {
    return "<tr><th scope=\"row\">" + esc(label) + "</th>" + cells.join("") + "</tr>";
  }

  function renderSavedPage(root) {
    var products = getSaved().map(byId).filter(Boolean);

    if (!products.length) {
      root.innerHTML =
        '<div class="sc-empty">' +
          "<p>Nothing saved yet. Browse the database and hit “Save to compare” on any product — it'll wait for you here.</p>" +
          '<p><a class="sc-btn sc-btn-primary" href="hub.html">Browse all products</a></p>' +
        "</div>";
      return;
    }

    var head = products.map(function (p) {
      return '<td class="sc-saved-col">' +
        '<a class="sc-saved-art" href="products/' + esc(p.id) + '.html">' +
          (p.imageUrl ? '<img src="' + esc(p.imageUrl) + '" alt="">' : "") +
        "</a>" +
        '<span class="sc-tile-brand">' + esc(p.brand) + "</span>" +
        '<a class="sc-saved-name" href="products/' + esc(p.id) + '.html">' + esc(p.name) + "</a>" +
        '<button type="button" class="sc-saved-remove" data-remove-id="' + esc(p.id) + '">Remove</button>' +
      "</td>";
    });

    // Saves cross categories, so metric rows come from the configs of the
    // categories actually present — a dash marks "does not apply".
    var factRows = [];
    var seenLabels = {};
    products.forEach(function (p) {
      cfgOf(p).tileFacts.forEach(function (f) {
        if (seenLabels[f.label]) return;
        seenLabels[f.label] = true;
        factRows.push(savedRowHTML(f.label, products.map(function (q) {
          return '<td class="sc-num">' + factOf(q, f.key) + "</td>";
        })));
      });
    });

    var anyStim = products.some(showsStimTag);

    var rows = [
      savedRowHTML("Category", products.map(function (p) { return "<td>" + esc(categoryLabelOf(p)) + "</td>"; }))
    ].concat(factRows, [
      savedRowHTML("Proprietary blend", products.map(function (p) { return "<td>" + blendHTML(p) + "</td>"; })),
      savedRowHTML("Servings", products.map(function (p) { return '<td class="sc-num">' + esc(p.servings) + "</td>"; })),
      savedRowHTML("Price tier", products.map(function (p) { return "<td>" + priceWordHTML(p) + "</td>"; }))
    ], anyStim ? [
      savedRowHTML("Stim tier", products.map(function (p) {
        return "<td>" + (showsStimTag(p) || categoryOf(p) === "pre-workout" ? esc(stimLabelOf(p)) : '<span class="sc-dim">—</span>') + "</td>";
      }))
    ] : [], [
      "<tr><th scope=\"row\">Links</th>" + products.map(function (p) {
        return '<td class="sc-saved-links">' +
          '<a class="sc-btn sc-btn-primary" href="products/' + esc(p.id) + '.html">Full breakdown</a>' +
          '<a class="sc-btn sc-btn-secondary" href="' + esc(p.affiliateUrl) + '" target="_blank" rel="sponsored nofollow noopener">View current price <span class="sc-ext" aria-hidden="true">&#8599;</span></a>' +
        "</td>";
      }).join("") + "</tr>"
    ]);

    root.innerHTML =
      '<p class="sc-count">' + products.length + " saved · stored only in this browser</p>" +
      '<div class="sc-table-scroll sc-saved-scroll">' +
        '<table class="sc-table sc-saved-table">' +
          "<tbody><tr><td></td>" + head.join("") + "</tr>" + rows.join("") + "</tbody>" +
        "</table>" +
      "</div>" +
      '<p class="sc-verify-note">Figures come from manufacturer labels and can change without notice — always verify against the current label on the product you buy.</p>' +
      '<p><button type="button" class="sc-clear-btn" id="sc-saved-clear">Clear all saved</button></p>';
  }

  // One delegated listener covers hub tiles, product pages, and the saved page.
  document.addEventListener("click", function (e) {
    var target = e.target;
    var saveBtn = target.closest ? target.closest("[data-save-id]") : null;
    if (saveBtn) {
      e.preventDefault();
      toggleSaved(saveBtn.getAttribute("data-save-id"));
      return;
    }
    var removeBtn = target.closest ? target.closest("[data-remove-id]") : null;
    if (removeBtn) {
      toggleSaved(removeBtn.getAttribute("data-remove-id"));
      return;
    }
    if (target.id === "sc-saved-clear") storeSaved([]);
  });

  /* ---------------------------------------------------------------------
   * Init
   * ------------------------------------------------------------------- */

  function init() {
    syncSaveUI(); // nav counter + save toggles work on every page

    if (typeof PRODUCTS === "undefined") {
      initReveal(); // product pages: motion only, no data renderers
      return;
    }

    var hub = document.getElementById("sc-products");
    var preview = document.getElementById("sc-preview-body");
    var starts = document.getElementById("sc-starts");
    var compare = document.getElementById("sc-compare-body");

    if (hub) {
      wireFilters();
      renderHub();
      injectCatalogLD();
      redirectLegacyHash();
    }

    if (preview) renderPreview();
    if (starts) renderStarts();

    if (compare) {
      wireCompare();
      renderCompare();
    }

    initReveal();
  }

  document.addEventListener("DOMContentLoaded", init);
})();
