/* Scoop Sense — filtering, sorting, and rendering.
 *
 * Loads AFTER data/products.js on every scripted page. Reads the globals
 * PRODUCTS and FEATURED_IDS; defines nothing else on window.
 *
 * Renderers, by page:
 *   hub.html      — #sc-products shop-style card grid + toolbar filters
 *   index.html    — #sc-preview-body database preview + #sc-starts picks
 *   compare.html  — #sc-compare-body sortable table
 *
 * Product detail pages are static files in products/ generated by
 * scripts/build-product-pages.js — regenerate after data changes.
 */

(function () {
  "use strict";

  // Category landing pages declare themselves via <body data-category="...">;
  // the dataset (grid AND compare rows) is then locked to that category.
  var PAGE_CATEGORY = document.body.getAttribute("data-category") || null;

  /* Filter state. The Simple and Advanced tabs are two ways to work ONE
   * chosen figure, not two filters: both start by picking the figure, and
   * the figure, the price tier, and the scoping controls carry across.
   *   figure    axis key the reader picked ("" = browse everything)
   *   bucket    index into that figure's ranges ("all" = off)
   *   dir       "" | "desc" | "asc" — sort on the chosen figure
   *   price     "all" | "Budget" | "Mid-range" | "Premium"
   *   target    the amount typed on the Advanced tab, in display units
   *   tolerance 0 = rank by closeness only; otherwise a hard +/- fraction
   */
  var state = {
    search: "",
    category: PAGE_CATEGORY || "all",
    brand: "all",
    mode: "simple",
    figure: "",
    bucket: "all",
    dir: "",
    price: "all",
    label: "all",
    target: undefined,
    tolerance: 0
  };

  // Back to an unfiltered page. Used by "Clear all" and by a fresh hash
  // arriving on the page already open, which has to forget the old view
  // before it reads the new one. Leaves `mode` alone: which tab a reader
  // works in is a preference, not a filter.
  function resetFilterState() {
    state.search = "";
    state.category = PAGE_CATEGORY || "all";
    state.brand = "all";
    state.figure = "";
    state.bucket = "all";
    state.dir = "";
    state.price = "all";
    state.label = "all";
    state.target = undefined;
    state.tolerance = 0;
  }

  /* Quality-of-label filters. Every one of these already exists as a badge or
   * is derivable from the ingredient list, and none of them could be filtered
   * on — a drug-tested athlete had to eyeball a badge across the whole grid,
   * which is the one filter that decides whether a product is usable at all. */
  var LABEL_FILTERS = [
    { value: "all", label: "Any label", test: function () { return true; } },
    { value: "tested", label: "Third-party tested",
      test: function (p) { return p.badges.indexOf("Third-Party Tested") !== -1; } },
    { value: "disclosed", label: "Fully disclosed", test: isDisclosed },
    { value: "noblend", label: "No blends at all",
      test: function (p) { return blendState(p) === "none"; } },
    // `only`: offered where that category is in scope, and nowhere else. A
    // dairy question on a creatine shelf is noise.
    { value: "dairyfree", label: "Dairy-free protein source", only: "protein",
      test: isDairyFreeSource }
  ];

  function labelFilterOf(value) {
    for (var i = 0; i < LABEL_FILTERS.length; i++) {
      if (LABEL_FILTERS[i].value === value) return LABEL_FILTERS[i];
    }
    return LABEL_FILTERS[0];
  }

  // Whether a label filter has anything to say about what is currently listed.
  function labelFilterApplies(f, pool) {
    if (!f.only) return true;
    return pool.some(function (p) { return categoryOf(p) === f.only; });
  }

  // Figures on offer for whatever category is in scope; see rebuildAxes().
  var AXES = [];
  var FIGURE_GROUPS = [];

  // Products predate the category field; missing means pre-workout.
  function categoryOf(p) {
    return p.category || "pre-workout";
  }

  function cfgOf(p) {
    return CATEGORY_CONFIG[categoryOf(p)] || CATEGORY_CONFIG["pre-workout"];
  }

  function categoryLabelOf(p) {
    var c = categoryOf(p);
    if (CATEGORY_CONFIG[c]) return CATEGORY_CONFIG[c].label;
    return c.charAt(0).toUpperCase() + c.slice(1);
  }

  /* ---------------------------------------------------------------------
   * Helpers
   * ------------------------------------------------------------------- */

  function esc(value) {
    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  // Caffeine bucket: matches the hub's caffeine <select> values.
  function bucketOf(p) {
    if (p.caffeineMg === 0) return "none";
    if (p.caffeineMg < 150) return "low";
    if (p.caffeineMg < 250) return "moderate";
    return "high";
  }

  function stimLabelOf(p) {
    var bucket = bucketOf(p);
    if (bucket === "none") return "Stim-free";
    if (bucket === "low") return "Low stim";
    if (bucket === "moderate") return "Moderate stim";
    return "High stim";
  }

  // "8 g" -> 8000, "350 mg" -> 350, "3,000 mg" -> 3000, unparseable -> null.
  // The comma matters: a comma-blind [\d.]+ matched the "000" in "3,000 mg"
  // and read it as 0 mg, and would have read "1,500 mg" as 500.
  function parseDoseMg(dose) {
    var m = /([\d.,]+)\s*(mg|g)\b/i.exec(dose || "");
    if (!m) return null;
    var n = parseFloat(m[1].replace(/,/g, ""));
    if (!isFinite(n)) return null;
    return m[2].toLowerCase() === "g" ? n * 1000 : n;
  }

  function findIngredient(p, re) {
    for (var i = 0; i < p.keyIngredients.length; i++) {
      if (re.test(p.keyIngredients[i].name)) return p.keyIngredients[i];
    }
    return null;
  }

  // Citrulline: distinguishes malate from pure L-citrulline — the two are
  // not interchangeable gram for gram.
  function citrullineOf(p) {
    var ing = findIngredient(p, /citrulline/i);
    if (!ing) return null;
    return { dose: ing.dose, form: /malate/i.test(ing.name) ? "malate" : "" };
  }

  function betaAlanineOf(p) {
    var ing = findIngredient(p, /beta[- ]alanine/i);
    return ing ? ing.dose : null;
  }

  /* Which storefront an affiliate link actually goes to.
   *
   * Every link on the site is Amazon today, but the retailer's name was
   * hardcoded into prose in two templates, so pointing a single product at a
   * brand's own store would have left the page naming the wrong destination —
   * on a site whose value is not making statements like that.
   *
   * Derived from the link so a swapped URL relabels itself: Amazon by host,
   * otherwise the brand, because a brand-direct link placed through a network
   * (Impact, Awin) resolves through a tracking host that is not the brand's
   * own domain. The optional `retailer` field overrides both, for a
   * third-party seller that is neither Amazon nor the brand. */
  function retailerOf(p) {
    if (p.retailer) return p.retailer;
    var m = /^https?:\/\/([^\/]+)/.exec(p.affiliateUrl || "");
    if (!m) return p.brand;
    return /(^|\.)amazon\./i.test(m[1]) ? "Amazon" : p.brand;
  }

  /* A blend's total is not a dose of anything named inside it.
   *
   * Bloom's "Performance Blend (L-Citrulline Malate, L-Citrulline, Beta
   * Alanine, Beet Root Extract)" is 4.68 g, and an ingredient-name match
   * finds citrulline in it — so the figure was being ranked against labels
   * that disclose 8 g of actual citrulline. That compares a sum to one of its
   * parts. The cell still shows "4.68 g blend", which is the honest reading;
   * it just cannot be ordered against a real dose.
   *
   * The qualifier in the dose string is the signal, not the ingredient name:
   * "Amino9 EAA blend — 6.7 g" is a pooled name whose total *is* the figure
   * the EAA column wants, and it carries no qualifier. */
  function isPooledDose(ing) {
    return /blend|proprietary|not individually/i.test(ing.dose || "");
  }

  /* Blends hide different things in different categories, and calling them
   * all one thing gets a label wrong either way.
   *
   *   proprietary  A combined total standing in for the doses of distinct
   *                actives — how much citrulline, how much caffeine. The
   *                dose itself is unknown.
   *   partial      "Whey protein blend (concentrate, isolate, hydrolysate)"
   *                at 25 g. The total is disclosed and is the protein
   *                figure; what is hidden is the ratio between the sources,
   *                which decides quality, not dose.
   *
   * Treating the second as fully disclosed is how eleven protein blends came
   * to carry a "Label fully disclosed" chip. Treating it as proprietary
   * would be the opposite error — a dose-hiding warning on a disclosed total.
   */
  function blendState(p) {
    if (p.badges.indexOf("Proprietary Blend") !== -1) return "proprietary";
    if (!findIngredient(p, /blend/i)) return "none";
    return categoryOf(p) === "pre-workout" ? "proprietary" : "partial";
  }

  function hasBlend(p) {
    return blendState(p) !== "none";
  }

  // A label is only fully disclosed if nothing on it is pooled. The badge is
  // hand-set in the data and cannot see the ingredient list.
  function isDisclosed(p) {
    return p.badges.indexOf("Fully Disclosed Label") !== -1 &&
      blendState(p) === "none";
  }

  /* The box says "product, brand, or ingredient", and on the category pages
   * it says source too — but it only ever read name, brand and ingredient
   * names. So "sucralose" matched one product while fifteen are sweetened
   * with it, and "stevia" matched two of seventeen. A shopper avoiding a
   * sweetener was being told the wrong answer silently, which is worse than
   * no search at all. The metric text fields and the flavour note carry
   * exactly those words, so they belong in the haystack. */
  function matchesSearch(p, term) {
    if (!term) return true;
    var bits = [p.name, p.brand, p.flavorsNote || ""];
    if (p.metrics) {
      for (var k in p.metrics) {
        if (typeof p.metrics[k] === "string") bits.push(p.metrics[k]);
      }
    }
    for (var i = 0; i < p.keyIngredients.length; i++) bits.push(p.keyIngredients[i].name);
    for (var j = 0; j < (p.badges || []).length; j++) bits.push(p.badges[j]);
    return bits.join(" ").toLowerCase().indexOf(term) !== -1;
  }

  function byName(a, b) {
    return a.name.localeCompare(b.name) || a.brand.localeCompare(b.brand);
  }

  // Is the grid currently ordered by distance from a typed amount?
  function isRanked() {
    return state.mode === "advanced" && !!state.figure && state.target !== undefined;
  }

  function applyFilters() {
    var term = state.search.trim().toLowerCase();
    var axis = state.figure ? axisByKey(state.figure) : null;
    var ranked = isRanked() && axis;

    var results = PRODUCTS.filter(function (p) {
      if (!matchesSearch(p, term)) return false;
      if (state.category !== "all" && categoryOf(p) !== state.category) return false;
      if (state.brand !== "all" && p.brand !== state.brand) return false;
      if (state.price !== "all" && priceWordOf(p) !== state.price) return false;
      if (state.label !== "all" && !labelFilterOf(state.label).test(p)) return false;
      if (!axis) return true;

      var v = factSortValue(p, axis.key);
      // Picking a figure means "show me labels that actually list it" — a
      // creatine search should not return every protein powder on file.
      if (v === -1) return false;

      if (state.bucket !== "all") {
        var range = axis.buckets[Number(state.bucket)];
        if (!range || !range.test(v)) return false;
      }
      // A tolerance turns the typed amount from a ranking into a cut-off.
      if (ranked && state.tolerance > 0 && !withinTolerance(p, axis, state.target)) {
        return false;
      }
      return true;
    });

    if (ranked) {
      var aim = state.target / axis.scale;
      results.sort(function (a, b) {
        var da = Math.abs(factSortValue(a, axis.key) - aim);
        var db = Math.abs(factSortValue(b, axis.key) - aim);
        return da !== db ? da - db : byName(a, b);
      });
    } else if (axis && state.dir) {
      results.sort(function (a, b) {
        var av = factSortValue(a, axis.key);
        var bv = factSortValue(b, axis.key);
        if (av !== bv) return state.dir === "asc" ? av - bv : bv - av;
        return byName(a, b);
      });
    } else {
      results.sort(byName);
    }

    return results;
  }

  /* ---------------------------------------------------------------------
   * Shared cell fragments
   * ------------------------------------------------------------------- */

  /* A dose cell is a figure plus, sometimes, a qualifier ("8 g malate",
   * "4.68 g blend"). Printing them as one string pushes the numerals off the
   * right-aligned edge, which is the whole point of a comparison column — so
   * the qualifier is floated to the left of the cell and the figure keeps the
   * edge. Splits "<number><unit>" from whatever follows it. */
  function doseCellHTML(dose, extraQual) {
    if (!dose) return '<span class="sc-dim">—</span>';
    var m = /^\s*([\d.]+\s*(?:mg|g|%))\s*(.*)$/i.exec(dose);
    var figure = m ? m[1] : dose;
    var qual = [m && m[2] ? m[2] : "", extraQual || ""].filter(Boolean).join(" ");
    // The qualifier slot is always emitted, even when empty: it reserves the
    // same width on every row, so the figures keep one shared right edge.
    return esc(figure) + '<span class="sc-qual">' + esc(qual) + "</span>";
  }

  function citrullineHTML(p) {
    var cit = citrullineOf(p);
    if (!cit) return '<span class="sc-dim">—</span>';
    return doseCellHTML(cit.dose, cit.form);
  }

  function betaHTML(p) {
    return doseCellHTML(betaAlanineOf(p));
  }

  function blendHTML(p) {
    var s = blendState(p);
    if (s === "proprietary") return "Yes";
    if (s === "partial") return '<span title="' + esc(PARTIAL_TIP) + '">Ratio only</span>';
    return '<span class="sc-dim">No</span>';
  }

  // "$" | "$$" | "$$$" -> plain-English cost-per-serving tier, with the basis
  // for the judgment exposed as a tooltip.
  /* The old wording claimed each tier was a computed third of the database.
   * It is not — the tiers are assigned by hand against the other products in
   * the same category, and the split is nowhere near even (electrolytes run
   * 10/24/5). Saying "the lowest third" made it sound like arithmetic. */
  var PRICE_BASIS = " Judged against the other products in the same category when the label was checked. We rank the tier rather than print a dollar figure, because prices move faster than we can re-check them — so use it to sort, not to budget.";
  var PRICE_TIPS = {
    Budget: "Among the cheaper options per full serving." + PRICE_BASIS,
    "Mid-range": "Around the middle of the category on cost per full serving." + PRICE_BASIS,
    Premium: "Among the more expensive options per full serving." + PRICE_BASIS
  };

  function priceWordOf(p) {
    return p.priceRange === "$" ? "Budget" : p.priceRange === "$$" ? "Mid-range" : "Premium";
  }

  function priceWordHTML(p) {
    var w = priceWordOf(p);
    return '<span title="' + esc(PRICE_TIPS[w]) + '">' + w + "</span>";
  }

  /* Config fact-key resolver — see the key grammar comment in
   * js/categories.js. Returns an HTML cell fragment; missing -> em-dash. */

  var DASH = '<span class="sc-dim">—</span>';

  function metricOf(p, key) {
    if (!p.metrics) return null;
    var v = p.metrics[key];
    return v === undefined || v === null || v === "" ? null : v;
  }

  function factOf(p, key) {
    if (key === "caffeineMg") {
      return p.caffeineMg === 0 ? "0 mg" : esc(p.caffeineMg) + " mg";
    }
    if (key === "servings") return esc(p.servings);
    if (key === "blend") return blendHTML(p);
    if (key === "stim") return esc(stimLabelOf(p));
    if (key === "price") return priceWordHTML(p);
    if (key === "protPct") {
      var pg = metricOf(p, "proteinG"), sg = metricOf(p, "servingG");
      if (!pg || !sg) return DASH;
      return Math.round((pg / sg) * 100) + "%";
    }
    if (key.indexOf("ing:") === 0) {
      var pattern = key.slice(4);
      if (/citrulline/.test(pattern)) return citrullineHTML(p);
      var ing = findIngredient(p, new RegExp(pattern, "i"));
      return ing ? doseCellHTML(ing.dose) : DASH;
    }
    if (key.indexOf("m:") === 0) {
      var parts = key.split(":");
      var v = metricOf(p, parts[1]);
      if (v === null) return DASH;
      return esc(v) + (parts[2] ? " " + parts[2] : "");
    }
    return DASH;
  }

  // Numeric twin for sorting; missing -> -1 so gaps sink to the bottom.
  function factSortValue(p, key) {
    if (key === "name") return (p.brand + " " + p.name).toLowerCase();
    if (key === "caffeineMg") return p.caffeineMg;
    if (key === "servings") return p.servings;
    if (key === "blend") return hasBlend(p) ? 1 : 0;
    if (key === "stim") return p.caffeineMg;
    if (key === "price") return p.priceRange === "$" ? 1 : p.priceRange === "$$" ? 2 : 3;
    if (key === "protPct") {
      var pg = metricOf(p, "proteinG"), sg = metricOf(p, "servingG");
      return pg && sg ? pg / sg : -1;
    }
    if (key.indexOf("ing:") === 0) {
      var ing = findIngredient(p, new RegExp(key.slice(4), "i"));
      if (!ing || isPooledDose(ing)) return -1;
      return parseDoseMg(ing.dose) || -1;
    }
    if (key.indexOf("m:") === 0) {
      var v = metricOf(p, key.split(":")[1]);
      return typeof v === "number" ? v : -1;
    }
    return 0;
  }

  /* ---------------------------------------------------------------------
   * Filter figures
   *
   * The filter starts with one question: which figure do you care about?
   * Creatine grams, caffeine, protein, beta-alanine, sodium. The answers come
   * from each category's own sortable numeric compare columns, so a category's
   * filters and its compare table can never disagree about which figures
   * matter, and a new category needs no extra configuration.
   *
   * An axis is one of those figures with everything the panel needs to work
   * it: the unit it reads in, the spread across the labels on file, and the
   * ranges cut from them.
   * ------------------------------------------------------------------- */

  // Products the page is allowed to show: a category page never leaves its
  // slice, and the hub narrows once a category is picked.
  function scopePool() {
    var cat = PAGE_CATEGORY || state.category;
    if (cat === "all") return PRODUCTS;
    return PRODUCTS.filter(function (p) { return categoryOf(p) === cat; });
  }

  // Unit factSortValue already reports the figure in.
  function rawUnitOf(key) {
    if (key === "caffeineMg") return "mg";
    if (key === "protPct") return "%";
    if (key.indexOf("ing:") === 0) return "mg"; // parseDoseMg normalises to mg
    if (key.indexOf("m:") === 0) {
      var parts = key.split(":");
      return parts.length > 2 ? parts[2] : "";
    }
    return "";
  }

  function axisDefsFor(cat) {
    var cfg = CATEGORY_CONFIG[cat];
    if (!cfg) return [];
    return cfg.compareCols
      .filter(function (c) { return c.sortable && c.num; })
      .map(function (c) { return { key: c.key, label: c.label }; });
  }

  /* The figure list, grouped the way a reader thinks about it.
   *
   * A category page offers that category's figures flat. The all-products hub
   * offers everything, grouped by the supplement the figure belongs to —
   * "Creatine" under Creatine, "Sodium" under Electrolytes — with the figures
   * that turn up in more than one category lifted into a shared group at the
   * top so caffeine is not filed under Pre-workout. */
  function buildFigureGroups() {
    var cat = PAGE_CATEGORY || state.category;
    if (cat !== "all") return [{ label: null, defs: axisDefsFor(cat) }];

    var slugs = Object.keys(CATEGORY_CONFIG);
    var seenIn = {};
    slugs.forEach(function (slug) {
      axisDefsFor(slug).forEach(function (d) {
        seenIn[d.key] = (seenIn[d.key] || 0) + 1;
      });
    });

    var shared = [];
    var groups = [];
    var claimed = {};

    slugs.forEach(function (slug) {
      var mine = [];
      axisDefsFor(slug).forEach(function (d) {
        if (claimed[d.key]) return;
        claimed[d.key] = true;
        if (seenIn[d.key] > 1) shared.push(d);
        else mine.push(d);
      });
      if (mine.length) groups.push({ label: CATEGORY_CONFIG[slug].label, defs: mine });
    });

    if (shared.length) groups.unshift({ label: "Any supplement", defs: shared });
    return groups;
  }

  // Caffeine's ranges carry meaning a reader already has (two cups of coffee),
  // so they stay hand-written. Every other axis splits its own observed range.
  var CAFFEINE_BUCKETS = [
    { label: "Stim-free (0 mg)", test: function (v) { return v === 0; } },
    { label: "Under 150 mg", test: function (v) { return v > 0 && v < 150; } },
    { label: "150–249 mg", test: function (v) { return v >= 150 && v < 250; } },
    { label: "250 mg and up", test: function (v) { return v >= 250; } }
  ];

  var PRICE_TIERS = ["Budget", "Mid-range", "Premium"];

  // A step a label would actually print: 1, 2, or 5 times a power of ten.
  function niceRound(v) {
    if (!isFinite(v) || v <= 0) return 0;
    var mag = Math.pow(10, Math.floor(Math.log(v) / Math.LN10));
    var n = v / mag;
    return (n < 1.5 ? 1 : n < 3.5 ? 2 : n < 7.5 ? 5 : 10) * mag;
  }

  function roundTo(v, step) {
    return Math.round((Math.round(v / step) * step) * 1e6) / 1e6;
  }

  function fmt(n) {
    return String(Math.round(n * 100) / 100);
  }

  // values must be sorted ascending.
  function quantile(values, q) {
    return values[Math.min(values.length - 1, Math.floor(q * values.length))];
  }

  /* Three ranges cut where the labels actually sit, not at even thirds of the
   * span: a third of the way along the citrulline axis is nowhere near a
   * third of the citrulline products.
   *
   * The cuts round to a step derived from the SPREAD rather than from each
   * cut's own magnitude — rounding 3.9 and 7.0 by magnitude lands both on 5
   * and the axis silently loses its ranges. Where the spread is too tight for
   * three, two are offered; where it is tight for two, the axis is sort-only. */
  function bucketsFor(axis) {
    if (axis.key === "caffeineMg") return CAFFEINE_BUCKETS;

    var values = axis.dvals;
    if (values.length < 3) return [];
    var lo = values[0];
    var hi = values[values.length - 1];
    if (!(hi > lo)) return [];

    var step = niceRound((hi - lo) / 6) || (hi - lo) / 6;
    var cut1 = roundTo(quantile(values, 1 / 3), step);
    var cut2 = roundTo(quantile(values, 2 / 3), step);
    if (cut1 <= lo) cut1 = roundTo(lo + step, step);
    if (cut2 <= cut1) cut2 = roundTo(cut1 + step, step);

    // "70%" reads right; "70 %" does not.
    var unit = !axis.unit ? "" : axis.unit === "%" ? "%" : " " + axis.unit;
    function under(cut) {
      var raw = cut / axis.scale;
      return { label: "Under " + fmt(cut) + unit, test: function (v) { return v < raw; } };
    }
    function from(cut) {
      var raw = cut / axis.scale;
      return { label: fmt(cut) + unit + " and up", test: function (v) { return v >= raw; } };
    }

    if (cut1 <= lo || cut1 >= hi) return [];
    if (cut2 >= hi) return [under(cut1), from(cut1)];

    var raw1 = cut1 / axis.scale;
    var raw2 = cut2 / axis.scale;
    return [
      under(cut1),
      { label: fmt(cut1) + "–" + fmt(cut2) + unit,
        test: function (v) { return v >= raw1 && v < raw2; } },
      from(cut2)
    ];
  }

  function rebuildAxes() {
    var pool = scopePool();
    FIGURE_GROUPS = buildFigureGroups();

    var defs = [];
    FIGURE_GROUPS.forEach(function (g) { defs = defs.concat(g.defs); });

    AXES = defs.map(function (def) {
      var axis = { key: def.key, label: def.label, unit: rawUnitOf(def.key), scale: 1 };

      if (def.key === "protPct") axis.scale = 100; // stored as a fraction

      var values = [];
      for (var i = 0; i < pool.length; i++) {
        var v = factSortValue(pool[i], def.key);
        if (typeof v === "number" && v >= 0) values.push(v);
      }
      values.sort(function (a, b) { return a - b; });
      axis.min = values.length ? values[0] : 0;
      axis.max = values.length ? values[values.length - 1] : 0;

      // Milligram figures that run into four digits (citrulline, EAAs) are
      // read as grams on the label they came from — show them the same way.
      if (axis.unit === "mg" && axis.max >= 2000) {
        axis.unit = "g";
        axis.scale = 0.001;
      }

      // Same figures in the units the reader sees, for cutting ranges.
      axis.dvals = values.map(function (v) { return v * axis.scale; });

      // Offer a band only if something is in it, and say how many. The
      // caffeine bands are hand-written, so "Under 150 mg" was on the menu
      // for a catalogue whose lowest caffeinated pre-workout is 155 mg —
      // picking it emptied the grid and the filter never said why.
      axis.buckets = bucketsFor(axis).map(function (b) {
        var n = 0;
        for (var k = 0; k < values.length; k++) if (b.test(values[k])) n++;
        return { label: b.label + " (" + n + ")", test: b.test, count: n };
      }).filter(function (b) { return b.count > 0; });
      return axis;
    });
  }

  function axisByKey(key) {
    for (var i = 0; i < AXES.length; i++) {
      if (AXES[i].key === key) return AXES[i];
    }
    return null;
  }

  function withinTolerance(p, axis, target) {
    var v = factSortValue(p, axis.key);
    if (v === -1) return false;
    var raw = target / axis.scale;
    // A target of zero has no percentage around it, so a stim-free search
    // falls back to the same fraction of the axis's own spread.
    var allowed = state.tolerance * (raw || (axis.max - axis.min) || 1);
    return Math.abs(v - raw) <= allowed;
  }

  function productLinkCell(p) {
    return '<a href="products/' + esc(p.id) + '.html">' +
      '<span class="sc-cell-brand">' + esc(p.brand) + "</span>" +
      '<span class="sc-cell-name">' + esc(p.name) + "</span></a>";
  }

  /* ---------------------------------------------------------------------
   * Product tiles (hub) — shop-style cards. The card links to the static
   * product page (products/<id>.html); the CTA row holds the two actions.
   * All fields escaped before interpolation.
   *
   * Tiles render p.imageUrl when present (affiliate-approved imagery
   * only); otherwise a generic stylized tub — never real packaging.
   * ------------------------------------------------------------------- */

  function monogramOf(p) {
    var words = (p.brand || "?").split(/\s+/);
    var mono = words[0].charAt(0) + (words[1] ? words[1].charAt(0) : "");
    return mono.toUpperCase();
  }

  // Mirrors tubSVG in scripts/build-product-pages.js — keep in sync.
  // The lid overlaps the body (y 6–50 against a body starting at 44) so it
  // reads as a lid, and it is lighter than the body, not darker: a lid drawn
  // below the page background floats off as a detached rectangle.
  function tubSVG(p) {
    var accent = p.accentColor || "#3A424D";
    return '<svg viewBox="0 0 200 240" xmlns="http://www.w3.org/2000/svg">' +
      '<rect x="34" y="6" width="132" height="44" rx="8" fill="#232830" stroke="#333A44"/>' +
      '<rect x="24" y="44" width="152" height="186" rx="14" fill="#191D23" stroke="#333A44"/>' +
      '<rect x="38" y="78" width="124" height="118" rx="6" fill="#F2EDE3"/>' +
      '<rect x="38" y="78" width="124" height="14" rx="6" fill="' + esc(accent) + '"/>' +
      '<text x="100" y="150" text-anchor="middle" font-family="Barlow Condensed, Arial Narrow, sans-serif" ' +
        'font-size="44" font-weight="700" fill="#17140F" letter-spacing="2">' + esc(monogramOf(p)) + "</text>" +
      '<rect x="56" y="166" width="88" height="3" fill="#17140F" opacity="0.75"/>' +
      '<rect x="56" y="176" width="88" height="2" fill="#17140F" opacity="0.3"/>' +
      '<rect x="56" y="184" width="62" height="2" fill="#17140F" opacity="0.3"/>' +
    "</svg>";
  }

  // Plain-English explanations surfaced as native tooltips on the tag chips.
  var STIM_TIPS = {
    none: "0 mg caffeine per serving. Stim-free is not effect-free — the other ingredients are still active.",
    low: "Under 150 mg caffeine per full serving — less than two small cups of coffee.",
    moderate: "150–249 mg caffeine per full serving — roughly two small cups of coffee.",
    high: "250 mg or more caffeine per full serving. The FDA cites about 400 mg per day for healthy adults."
  };
  var DISCLOSED_TIP = "Every active ingredient and its dosage is individually listed on the label. No proprietary blends.";
  var BLEND_TIP = "One or more combined blend totals hide the individual ingredient amounts inside.";
  var PARTIAL_TIP = "The blend's total is on the label, but not the ratio between the sources inside it — so the total is known and the split is not.";
  var TESTED_TIP = "Certified by an independent banned-substance testing program (NSF Certified for Sport, Informed Sport, or Informed Choice), per the label or brand page.";
  var BEGINNER_TIP = "A reasonable first tub: moderate or no caffeine, a fully disclosed label, and nothing on the panel that surprises a new user.";
  var BUDGET_TIP = "Cost per full serving sits in the lowest third of this database while the label still discloses its doses.";
  var DAIRYFREE_TIP = "The protein source named on the panel carries no whey, casein, or milk. This reads the source line only — check the label's own allergen statement before buying.";

  /* Protein only, and read straight off the panel's source line rather than
   * inferred from the name: whey, casein and milk are dairy, plants and hemp
   * are not. A product whose source line says nothing stays out — "unstated"
   * is not the same as "safe", and this is the one figure on a protein label
   * a lactose-intolerant reader cannot afford a guess on. */
  function isDairyFreeSource(p) {
    if (categoryOf(p) !== "protein") return false;
    var src = (p.metrics && p.metrics.source) || "";
    if (!src) return false;
    return !/whey|casein|milk|lactose/i.test(src);
  }

  // Stim tag rule: pre-workout tiles always carry one; every other category
  // shows one only when the formula is actually caffeinated — a "Stim-Free"
  // chip on a protein shelf is noise, but caffeine anywhere deserves a flag.
  // (The config stimBadges flag drives the "at a glance" panel, not this tag.)
  function showsStimTag(p) {
    return categoryOf(p) === "pre-workout" || p.caffeineMg > 0;
  }

  function tagsHTML(p, limit) {
    var tags = [];
    var bucket = bucketOf(p);
    if (showsStimTag(p)) {
      var stimClass = "sc-tag";
      if (bucket === "high") stimClass += " sc-tag-caution";
      if (bucket === "none") stimClass += " sc-tag-calm";
      tags.push('<span class="' + stimClass + '" title="' + esc(STIM_TIPS[bucket]) + '">' + esc(stimLabelOf(p)) + "</span>");
    }
    var blend = blendState(p);
    if (blend === "proprietary") {
      tags.push('<span class="sc-tag sc-tag-caution" title="' + esc(BLEND_TIP) + '">Proprietary blend</span>');
    } else if (blend === "partial") {
      tags.push('<span class="sc-tag" title="' + esc(PARTIAL_TIP) + '">Blend ratio undisclosed</span>');
    } else if (isDisclosed(p)) {
      tags.push('<span class="sc-tag" title="' + esc(DISCLOSED_TIP) + '">Label fully disclosed</span>');
    }
    if (p.badges.indexOf("Third-Party Tested") !== -1) {
      tags.push('<span class="sc-tag sc-tag-calm" title="' + esc(TESTED_TIP) + '">Third-party tested</span>');
    }
    if (isDairyFreeSource(p)) {
      tags.push('<span class="sc-tag sc-tag-calm" title="' + esc(DAIRYFREE_TIP) + '">Dairy-free source</span>');
    }
    if (p.badges.indexOf("Beginner Friendly") !== -1) {
      tags.push('<span class="sc-tag" title="' + esc(BEGINNER_TIP) + '">Beginner friendly</span>');
    }
    if (p.badges.indexOf("Budget Pick") !== -1) {
      tags.push('<span class="sc-tag" title="' + esc(BUDGET_TIP) + '">Budget pick</span>');
    }
    // Tiles cap the row so one product's five tags can't push its facts panel
    // out of line with the rest of the grid; product pages show all of them.
    return (limit ? tags.slice(0, limit) : tags).join("");
  }

  function tileFactHTML(label, valueHTML) {
    return '<span class="sc-tile-fact">' +
      '<span class="sc-tile-fact-label">' + label + "</span>" +
      '<span class="sc-tile-fact-value">' + valueHTML + "</span>" +
    "</span>";
  }

  function tileHTML(p) {
    var accent = p.accentColor ? ' style="--sc-p-accent:' + esc(p.accentColor) + '"' : "";
    var page = "products/" + esc(p.id) + ".html";

    return '<article class="sc-tile" id="p-' + esc(p.id) + '"' + accent + ">" +
      '<a class="sc-tile-link" href="' + page + '" ' +
        'aria-label="Full label breakdown: ' + esc(p.brand + " " + p.name) + '">' +
        // Every product image is a transparent cutout, so they all share the
        // same dark stage — no per-product background to match.
        '<span class="sc-tile-art" aria-hidden="true">' +
          // referrerpolicy: several brand CDNs refuse hotlinks that send a
          // referrer, and imageUrl is a retailer URL for products without a
          // locally stored render.
          (p.imageUrl
            ? '<img src="' + esc(p.imageUrl) + '" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer">'
            : tubSVG(p)) +
        "</span>" +
        '<span class="sc-tile-top">' +
          '<span class="sc-tile-brand">' + esc(p.brand) + "</span>" +
          '<span class="sc-tile-name">' + esc(p.name) + "</span>" +
        "</span>" +
        '<span class="sc-tile-tags">' + tagsHTML(p, 3) + "</span>" +
        '<span class="sc-tile-facts">' +
          '<span class="sc-tile-facts-title">Label data</span>' +
          cfgOf(p).tileFacts.map(function (f) {
            return tileFactHTML(esc(f.label), factOf(p, f.key));
          }).join("") +
          '<span class="sc-tile-foot">' +
            "<span>" + esc(p.servings) + " servings</span>" +
            "<span>" + priceWordHTML(p) + "</span>" +
          "</span>" +
        "</span>" +
      "</a>" +
      // The tile itself is the link to the breakdown, so the row underneath
      // carries only the two things that are not "read this label": the
      // outbound price check and the shortlist toggle.
      '<div class="sc-tile-ctas">' +
        '<a class="sc-tile-price" href="' + esc(p.affiliateUrl) + '" ' +
          'target="_blank" rel="sponsored nofollow noopener" ' +
          'aria-label="Check current price for ' + esc(p.brand + " " + p.name) +
          ' at ' + esc(retailerOf(p)) + ' (affiliate link)">Check price <span class="sc-ext" aria-hidden="true">&#8599;</span></a>' +
        // Title carries the label the icon-only button hides visually.
        "" +
        saveBtnHTML(p) +
      "</div>" +
    "</article>";
  }

  /* ---------------------------------------------------------------------
   * Hub
   * ------------------------------------------------------------------- */

  /* The unnarrowed hub is 187 tiles — 48 desktop screens, 146 on a phone.
   * A reader who has not filtered yet is looking for a way in, not a way
   * through, so draw a readable first helping and let them ask for more. */
  var PAGE_SIZE = 24;
  var shown = PAGE_SIZE;

  /* Built here rather than in each page's markup, like the filter panel: the
   * five browse pages ship no HTML for it. */
  function showMoreRow(list) {
    var row = document.getElementById("sc-more-row");
    if (row) return row;

    row = document.createElement("div");
    row.className = "sc-more-row";
    row.id = "sc-more-row";

    var btn = document.createElement("button");
    btn.type = "button";
    btn.id = "sc-more";
    btn.className = "sc-btn sc-btn-secondary";
    btn.addEventListener("click", function () {
      shown += PAGE_SIZE;
      // keepShown: this is the one render that must not go back to page one.
      renderHub(true);
      // The button moves down as tiles appear above it; put focus back on it
      // so a keyboard reader is not dropped at the top of a longer grid.
      var again = document.getElementById("sc-more");
      if (again && !again.hidden) again.focus();
    });

    row.appendChild(btn);
    list.parentNode.insertBefore(row, list.nextSibling);
    return row;
  }

  /* The label filters were reachable only inside a panel that starts
   * collapsed, so the one filter that decides whether a product is usable at
   * all — independently tested, dairy-free — was invisible to anyone who did
   * not go hunting. Same state as the panel's Label select, one tap, above the
   * grid. Zero-count filters are left out rather than offered as dead ends. */
  function renderQuickFilters() {
    var count = document.getElementById("sc-count");
    if (!count) return;

    var row = document.getElementById("sc-quick");
    if (!row) {
      row = document.createElement("nav");
      row.id = "sc-quick";
      row.className = "sc-quick";
      row.setAttribute("aria-label", "Quick label filters");
      row.addEventListener("click", function (event) {
        var chip = event.target.closest("[data-label]");
        if (!chip) return;
        var value = chip.getAttribute("data-label");
        // Tapping the chip that is already on is how you turn it off.
        state.label = state.label === value ? "all" : value;
        renderFilterPanel();
        refreshFilterCount();
        renderHub(); // redraws these chips too, so nothing is done here
      });
      count.parentNode.insertBefore(row, count);
    }

    var pool = scopePool();
    row.innerHTML = LABEL_FILTERS.filter(function (f) {
      return f.value !== "all" && labelFilterApplies(f, pool);
    }).map(function (f) {
      var n = 0;
      for (var i = 0; i < pool.length; i++) if (f.test(pool[i])) n++;
      if (!n) return "";
      var on = state.label === f.value;
      return '<button type="button" class="sc-chip' + (on ? " sc-chip-active" : "") +
        '" data-label="' + esc(f.value) + '" aria-pressed="' + on + '">' +
        esc(f.label) + " (" + n + ")</button>";
    }).join("");
  }

  function renderHub(keepShown) {
    var list = document.getElementById("sc-products");
    var count = document.getElementById("sc-count");
    var empty = document.getElementById("sc-empty");
    var results = applyFilters();

    // Every path that changes a filter ends here, so this is the one place
    // the address bar has to be kept honest.
    writeHashState();

    // A new filter is a new question: answer it from the top.
    if (!keepShown) shown = PAGE_SIZE;

    var page = results.slice(0, shown);
    list.innerHTML = page.map(tileHTML).join("");

    var left = results.length - page.length;
    var moreBtn = showMoreRow(list).querySelector("button");
    moreBtn.hidden = left <= 0;
    document.getElementById("sc-more-row").hidden = left <= 0;
    if (left > 0) {
      moreBtn.textContent = "Show " + Math.min(PAGE_SIZE, left) + " more · " +
        left + " still to see";
    }

    if (count) {
      // First number is always what is on screen, second the set it was drawn
      // from — the matches while tiles are still held back, otherwise what the
      // page is scoped to. "2 of 187" is a lie once a category is picked, and
      // "187 of 187" is a lie while only 24 tiles are drawn.
      var pool = scopePool().length;
      count.textContent = "Showing " + page.length + " of " +
        (left > 0 ? results.length : pool) + " products" +
        (isRanked() ? " — closest first" : "");
    }
    if (empty) {
      empty.hidden = results.length !== 0;
    }

    renderQuickFilters();

    // Fresh tiles from a filter change reveal as they enter the viewport.
    if (revealObserver) initReveal();
  }

  /* The brand list is cut from whatever category is in scope, and recut when
   * that changes. Left unscoped the hub offers all 90-odd brands on a
   * category that holds a dozen, and picking one of the other 78 empties the
   * grid with nothing on screen explaining why. */
  function populateBrands(select) {
    var pool = scopePool();
    var brands = [];
    for (var i = 0; i < pool.length; i++) {
      if (brands.indexOf(pool[i].brand) === -1) brands.push(pool[i].brand);
    }
    brands.sort(function (a, b) { return a.localeCompare(b); });

    // A brand that survives the category switch keeps its selection; one that
    // does not falls back to all rather than filtering on something unlisted.
    if (state.brand !== "all" && brands.indexOf(state.brand) === -1) state.brand = "all";

    var html = '<option value="all">All brands</option>';
    for (var j = 0; j < brands.length; j++) {
      html += '<option value="' + esc(brands[j]) + '">' + esc(brands[j]) + "</option>";
    }
    select.innerHTML = html;
    select.value = state.brand;
  }

  function populateCategories(select) {
    var cats = [];
    for (var i = 0; i < PRODUCTS.length; i++) {
      var c = categoryOf(PRODUCTS[i]);
      if (cats.indexOf(c) === -1) cats.push(c);
    }
    if (cats.length < 2) { select.hidden = true; return; }
    cats.sort();
    for (var j = 0; j < cats.length; j++) {
      var option = document.createElement("option");
      option.value = cats[j];
      option.textContent = CATEGORY_CONFIG[cats[j]]
        ? CATEGORY_CONFIG[cats[j]].label
        : cats[j].charAt(0).toUpperCase() + cats[j].slice(1);
      select.appendChild(option);
    }
  }

  /* ---------------------------------------------------------------------
   * Filter panel
   *
   * Built here rather than written into each page's markup, so the five
   * browse pages ship an empty container and every category gets the same
   * controls over its own figures.
   *
   * Both tabs start with the same question — which figure? — and differ only
   * in what they do with the answer. Simple narrows it to a range and sorts
   * on it. Advanced takes an amount and orders by nearness to it.
   *
   * The markup is built once per figure list (a category switch rebuilds it).
   * Everything after that updates in place: replacing the panel mid-keystroke
   * would take the caret out of the input and the focus off the select.
   * ------------------------------------------------------------------- */

  var TOLERANCES = [
    { value: 0, label: "Any distance — just rank them" },
    { value: 0.1, label: "Within 10%" },
    { value: 0.25, label: "Within 25%" },
    { value: 0.5, label: "Within 50%" }
  ];

  var DIRECTIONS = [
    { value: "", label: "Name (A–Z)" },
    { value: "desc", label: "High to low" },
    { value: "asc", label: "Low to high" }
  ];

  function optionsHTML(items, selected) {
    return items.map(function (it) {
      return '<option value="' + esc(it.value) + '"' +
        (String(it.value) === String(selected) ? " selected" : "") + ">" +
        esc(it.label) + "</option>";
    }).join("");
  }

  // The figure list, with the hub's optgroups intact.
  function figureOptionsHTML() {
    var html = '<option value="">Everything on file</option>';
    FIGURE_GROUPS.forEach(function (group) {
      var opts = group.defs.map(function (d) {
        return '<option value="' + esc(d.key) + '"' +
          (d.key === state.figure ? " selected" : "") + ">" + esc(d.label) + "</option>";
      }).join("");
      html += group.label
        ? '<optgroup label="' + esc(group.label) + '">' + opts + "</optgroup>"
        : opts;
    });
    return html;
  }

  function fieldHTML(label, id, controlHTML) {
    return '<div class="sc-field">' +
      '<label class="sc-field-label" for="' + id + '">' + esc(label) + "</label>" +
      controlHTML +
    "</div>";
  }

  function selectHTML(id, inner) {
    return '<select class="sc-select" id="' + id + '">' + inner + "</select>";
  }

  function tabHTML(mode, label) {
    var on = state.mode === mode;
    return '<button type="button" class="sc-tab" role="tab" id="sc-tab-' + mode + '" ' +
      'data-mode="' + mode + '" aria-selected="' + on + '" ' +
      'aria-controls="sc-panel-' + mode + '" tabindex="' + (on ? "0" : "-1") + '">' +
      esc(label) + "</button>";
  }

  function renderFilterPanel() {
    var panel = document.getElementById("sc-filters");
    if (!panel) return;

    var priceOptions = optionsHTML(
      [{ value: "all", label: "Any price" }].concat(PRICE_TIERS.map(function (t) {
        return { value: t, label: t };
      })), state.price);

    // Counts, so "Third-party tested" never looks like an empty promise.
    var pool = scopePool();

    // A label filter the new category cannot answer would empty the grid with
    // nothing on screen explaining why — same rule as populateBrands.
    if (state.label !== "all" && !labelFilterApplies(labelFilterOf(state.label), pool)) {
      state.label = "all";
    }

    var labelOptions = optionsHTML(LABEL_FILTERS.filter(function (f) {
      return labelFilterApplies(f, pool);
    }).map(function (f) {
      if (f.value === "all") return { value: f.value, label: f.label };
      var n = 0;
      for (var i = 0; i < pool.length; i++) if (f.test(pool[i])) n++;
      return { value: f.value, label: f.label + " (" + n + ")" };
    }), state.label);

    panel.innerHTML =
      '<div class="sc-tabs" role="tablist" aria-label="Filter mode">' +
        tabHTML("simple", "Simple") + tabHTML("advanced", "Advanced") +
      "</div>" +

      '<div class="sc-fpanel" id="sc-panel-simple" role="tabpanel" ' +
        'aria-labelledby="sc-tab-simple"' + (state.mode === "simple" ? "" : " hidden") + ">" +
        '<div class="sc-fields">' +
          fieldHTML("Filter by", "sc-figure", selectHTML("sc-figure", figureOptionsHTML())) +
          fieldHTML("Amount", "sc-range", selectHTML("sc-range", "")) +
          fieldHTML("Sort", "sc-dir", selectHTML("sc-dir", optionsHTML(DIRECTIONS, state.dir))) +
          fieldHTML("Price", "sc-price", selectHTML("sc-price", priceOptions)) +
          fieldHTML("Label", "sc-label", selectHTML("sc-label", labelOptions)) +
        "</div>" +
        '<p class="sc-fnote" id="sc-note-simple"></p>' +
      "</div>" +

      '<div class="sc-fpanel" id="sc-panel-advanced" role="tabpanel" ' +
        'aria-labelledby="sc-tab-advanced"' + (state.mode === "advanced" ? "" : " hidden") + ">" +
        '<div class="sc-fields">' +
          fieldHTML("Filter by", "sc-figure-adv", selectHTML("sc-figure-adv", figureOptionsHTML())) +
          fieldHTML("Closest to", "sc-target",
            '<span class="sc-numwrap">' +
              '<input class="sc-input sc-numinput" type="number" inputmode="decimal" ' +
                'min="0" step="any" id="sc-target" value="' +
                (state.target === undefined ? "" : esc(state.target)) + '">' +
              '<span class="sc-numunit" id="sc-target-unit" aria-hidden="true"></span>' +
            "</span>") +
          fieldHTML("Match within", "sc-tolerance",
            selectHTML("sc-tolerance", optionsHTML(TOLERANCES, state.tolerance))) +
          fieldHTML("Price", "sc-price-adv", selectHTML("sc-price-adv", priceOptions)) +
          fieldHTML("Label", "sc-label-adv", selectHTML("sc-label-adv", labelOptions)) +
        "</div>" +
        '<p class="sc-fnote" id="sc-note-advanced"></p>' +
      "</div>";

    syncFigureUI();
  }

  /* Everything downstream of the chosen figure: its ranges, its unit, the
   * span worth aiming at, and whether the controls that need a figure are
   * live at all. Rewrites those controls only, never the panel. */
  function syncFigureUI() {
    var axis = state.figure ? axisByKey(state.figure) : null;
    var range = document.getElementById("sc-range");
    var dir = document.getElementById("sc-dir");
    var target = document.getElementById("sc-target");
    var unit = document.getElementById("sc-target-unit");
    var tol = document.getElementById("sc-tolerance");
    if (!range) return;

    var ranges = [{ value: "all", label: "Any amount" }];
    if (axis) {
      axis.buckets.forEach(function (b, i) { ranges.push({ value: i, label: b.label }); });
    }
    range.innerHTML = optionsHTML(ranges, state.bucket);
    range.disabled = !axis || !axis.buckets.length;
    dir.disabled = !axis;
    target.disabled = !axis;
    tol.disabled = !axis;

    if (axis) {
      var lo = fmt(axis.min * axis.scale);
      var hi = fmt(axis.max * axis.scale);
      target.placeholder = lo + "–" + hi;
      target.setAttribute("aria-label",
        "Amount of " + axis.label + (axis.unit ? " in " + axis.unit : "") +
        " to get closest to, between " + lo + " and " + hi);
      unit.textContent = axis.unit;
    } else {
      target.placeholder = "—";
      target.setAttribute("aria-label", "Pick a figure first");
      unit.textContent = "";
    }

    var simple = document.getElementById("sc-note-simple");
    var advanced = document.getElementById("sc-note-advanced");
    if (axis) {
      simple.textContent = "Showing only labels that list " + axis.label.toLowerCase() +
        ". Narrow it to an amount, sort high to low or low to high, and set a price tier — " +
        "they all apply together.";
      advanced.textContent = "Type the " + axis.label.toLowerCase() +
        " you are after and the grid reorders by how close each label sits to it, " +
        "closest first. “Match within” drops anything further out than that.";
    } else {
      simple.textContent = "Start by picking the figure you care about — creatine, caffeine, " +
        "protein, beta-alanine, sodium. Everything else here then works on that figure.";
      advanced.textContent = "Pick a figure first, then type the amount you are after and " +
        "the grid reorders by how close each label sits to it.";
    }
  }

  // A collapsed panel must not hide the fact that it is doing something.
  function refreshFilterCount() {
    var badge = document.getElementById("sc-filters-count");
    if (!badge) return;
    var n = 0;
    if (state.figure) n++;
    if (state.bucket !== "all") n++;
    if (state.dir) n++;
    if (state.price !== "all") n++;
    if (state.label !== "all") n++;
    if (state.target !== undefined) n++;
    badge.textContent = n ? String(n) : "";
  }

  function setMode(mode) {
    state.mode = mode;
    var tabs = document.querySelectorAll("[data-mode]");
    for (var i = 0; i < tabs.length; i++) {
      var on = tabs[i].getAttribute("data-mode") === mode;
      tabs[i].setAttribute("aria-selected", on ? "true" : "false");
      tabs[i].setAttribute("tabindex", on ? "0" : "-1");
      var pane = document.getElementById("sc-panel-" + tabs[i].getAttribute("data-mode"));
      if (pane) pane.hidden = !on;
    }
  }

  function wireFilters() {
    var search = document.getElementById("sc-search");
    var category = document.getElementById("sc-category");
    var brand = document.getElementById("sc-brand");
    var clear = document.getElementById("sc-clear");
    var filtersBtn = document.getElementById("sc-filters-btn");
    var filtersPanel = document.getElementById("sc-filters");

    // A shared link is read once, before any control is built, so everything
    // below renders already wearing the state it asked for.
    readHashState();

    if (search) {
      search.value = state.search;
      search.addEventListener("input", function () {
        state.search = search.value;
        renderHub();
      });
    }

    if (category) {
      populateCategories(category);
      category.value = state.category;
      category.addEventListener("change", function () {
        state.category = category.value;
        // Different category, different figures: a figure set against the old
        // list would silently filter on something no longer on offer.
        state.figure = "";
        state.bucket = "all";
        state.dir = "";
        state.target = undefined;
        rebuildAxes();
        // Brands are per-category too — see populateBrands.
        if (brand) populateBrands(brand);
        renderFilterPanel();
        refreshFilterCount();
        renderHub();
      });
    }

    if (brand) {
      populateBrands(brand);
      brand.addEventListener("change", function () {
        state.brand = brand.value;
        renderHub();
      });
    }

    rebuildAxes();
    renderFilterPanel();
    refreshFilterCount();

    if (filtersPanel) {
      filtersPanel.addEventListener("change", function (event) {
        var el = event.target;

        // The two tabs each carry their own copy of the shared controls, so
        // whichever one the reader touched, the other has to follow.
        function mirror(id, value) {
          var twin = document.getElementById(id);
          if (twin) twin.value = value;
        }

        if (el.id === "sc-figure" || el.id === "sc-figure-adv") {
          state.figure = el.value;
          // The old range index and the old amount meant something on the old
          // figure; carrying them over would filter on a number nobody typed.
          state.bucket = "all";
          state.target = undefined;
          var typed = document.getElementById("sc-target");
          if (typed) typed.value = "";
          mirror(el.id === "sc-figure" ? "sc-figure-adv" : "sc-figure", el.value);
          syncFigureUI();
        } else if (el.id === "sc-range") {
          state.bucket = el.value;
        } else if (el.id === "sc-dir") {
          state.dir = el.value;
        } else if (el.id === "sc-price" || el.id === "sc-price-adv") {
          state.price = el.value;
          mirror(el.id === "sc-price" ? "sc-price-adv" : "sc-price", el.value);
        } else if (el.id === "sc-label" || el.id === "sc-label-adv") {
          state.label = el.value;
          mirror(el.id === "sc-label" ? "sc-label-adv" : "sc-label", el.value);
        } else if (el.id === "sc-tolerance") {
          state.tolerance = parseFloat(el.value) || 0;
        } else {
          return;
        }

        refreshFilterCount();
        renderHub();
      });

      filtersPanel.addEventListener("input", function (event) {
        if (event.target.id !== "sc-target") return;
        var raw = event.target.value.trim();
        var n = parseFloat(raw);
        state.target = raw === "" || !isFinite(n) ? undefined : n;
        refreshFilterCount();
        renderHub();
      });

      // A tablist takes arrow keys, not Tab: the inactive tab carries
      // tabindex="-1", so without this it cannot be reached by keyboard.
      filtersPanel.addEventListener("keydown", function (event) {
        if (!event.target.closest || !event.target.closest("[data-mode]")) return;
        var order = ["simple", "advanced"];
        var at = order.indexOf(state.mode);
        var next = null;
        if (event.key === "ArrowRight" || event.key === "ArrowDown") next = order[(at + 1) % 2];
        else if (event.key === "ArrowLeft" || event.key === "ArrowUp") next = order[(at + 1) % 2];
        else if (event.key === "Home") next = order[0];
        else if (event.key === "End") next = order[1];
        if (!next) return;
        event.preventDefault();
        setMode(next);
        document.getElementById("sc-tab-" + next).focus();
      });

      filtersPanel.addEventListener("click", function (event) {
        var tab = event.target.closest("[data-mode]");
        if (!tab) return;
        setMode(tab.getAttribute("data-mode"));
        // Simple sorts; Advanced ranks by nearness. Switching tabs switches
        // which of the two is in charge, so the grid has to be redrawn.
        renderHub();
      });
    }

    function clearAll() {
      resetFilterState();
      if (search) search.value = "";
      if (category) category.value = "all";
      if (brand) populateBrands(brand);
      rebuildAxes();
      renderFilterPanel();
      refreshFilterCount();
      renderHub();
      if (search) search.focus();
    }

    if (clear) clear.addEventListener("click", clearAll);

    /* The category chips are links, and four of the five point at a category
     * page — a real navigation, a fresh load, and readHashState() above runs
     * again. Pre-workout is the exception: it has no landing page of its own,
     * so its chip points at this page's own hash (hub.html#cat-pre-workout).
     * Same document, no reload, nothing re-reads the hash — the one chip that
     * looked broken while the other four worked. Filter writes use
     * replaceState, so they never fire this. */
    window.addEventListener("hashchange", function () {
      // The category pages carry their own in-page "Compare" link. That is a
      // jump, not a filter change — clearing the filters underneath it would
      // throw away the view the reader built before they clicked.
      if (isPlainAnchor(location.hash)) { jumpToAnchor(true); return; }
      resetFilterState();
      readHashState();
      if (search) search.value = state.search;
      if (category) category.value = state.category;
      if (brand) populateBrands(brand);
      rebuildAxes();
      renderFilterPanel();
      refreshFilterCount();
      renderHub();
    });

    // The dead end needs its own way out — the toolbar's "Clear all" can be
    // scrolled well off screen by the time a reader hits an empty result.
    var emptyClear = document.getElementById("sc-empty-clear");
    if (emptyClear) emptyClear.addEventListener("click", clearAll);

    if (filtersBtn && filtersPanel) {
      filtersBtn.addEventListener("click", function () {
        filtersPanel.hidden = !filtersPanel.hidden;
        filtersBtn.setAttribute("aria-expanded", filtersPanel.hidden ? "false" : "true");
        // See the sc-toolbar.sc-open note in the stylesheet.
        var bar = filtersBtn.closest(".sc-toolbar");
        if (bar) bar.classList.toggle("sc-open", !filtersPanel.hidden);
      });
    }
  }

  /* ---------------------------------------------------------------------
   * URL state
   *
   * A narrowed view is the thing worth sending someone — "creatine, high to
   * low, budget" is an answer, hub.html is not. Both the toolbar and the
   * filter panel write themselves into the hash, and a link written before
   * any of this (hub.html#cat-creatine) still reads back as its category.
   * ------------------------------------------------------------------- */

  // ":" is legal in a fragment and the axis keys are full of it (m:creatineG:g).
  // Leaving it raw is the difference between a readable link and a wall of %3A.
  function encHash(value) {
    return encodeURIComponent(value).replace(/%3A/g, ":");
  }

  /* Reads a shared link back into `state`. Everything is checked against what
   * this page actually offers — a hash is a stranger's typing, and a figure
   * from a creatine link means nothing on the protein page. */
  function readHashState() {
    var raw = location.hash.replace(/^#/, "");
    if (!raw) return;

    var got = {};
    raw.split("&").forEach(function (part) {
      var legacy = /^cat-([a-z-]+)$/.exec(part);
      if (legacy) { got.cat = legacy[1]; return; }
      var at = part.indexOf("=");
      if (at > 0) got[part.slice(0, at)] = decodeURIComponent(part.slice(at + 1));
    });

    if (!PAGE_CATEGORY && got.cat && CATEGORY_CONFIG[got.cat]) state.category = got.cat;
    if (got.q) state.search = got.q;
    if (got.mode === "advanced") state.mode = "advanced";
    if (PRICE_TIERS.indexOf(got.price) !== -1) state.price = got.price;
    if (got.label && got.label !== "all" && labelFilterOf(got.label).value === got.label &&
        labelFilterApplies(labelFilterOf(got.label), scopePool())) {
      state.label = got.label;
    }

    // Brand and figure are both cut from the category, so they can only be
    // checked once that is settled above.
    if (got.brand && scopePool().some(function (p) { return p.brand === got.brand; })) {
      state.brand = got.brand;
    }

    rebuildAxes();
    var axis = got.fig ? axisByKey(got.fig) : null;
    if (!axis) return; // no figure asked for, or one this category does not carry
    state.figure = axis.key;

    var i = parseInt(got.range, 10);
    if (i >= 0 && i < axis.buckets.length) state.bucket = String(i);
    if (got.sort === "desc" || got.sort === "asc") state.dir = got.sort;

    var near = parseFloat(got.near);
    if (isFinite(near) && near >= 0) state.target = near;

    var within = parseFloat(got.within);
    if (TOLERANCES.some(function (t) { return t.value === within; })) state.tolerance = within;
  }

  /* Mirrors `state` back out. replaceState rather than assigning location.hash:
   * changing a filter is not a navigation, and writing thirty of them into
   * history turns the back button into an undo log nobody asked for. */
  /* "#compare" names an element to jump to; "#cat-creatine" and
   * "#fig=m:proteinG:g&sort=desc" are filter state. Telling them apart keeps
   * each from overwriting the other. */
  function isPlainAnchor(hash) {
    var raw = (hash || "").replace(/^#/, "");
    if (!raw || raw.indexOf("=") !== -1 || /^cat-/.test(raw) || /^p-/.test(raw)) return false;
    return !!document.getElementById(raw);
  }

  /* The browser jumps to #compare during parse, while the section it points at
   * holds an empty <tbody> and the grid above it is an empty <div>. Both fill
   * in afterwards, pushing the table thousands of pixels down from wherever
   * the jump landed — so "Compare all protein powders" put the reader back at
   * the top of the grid they were trying to leave. Nothing retried it. Do the
   * jump again once the rows exist. */
  function jumpToAnchor(force) {
    if (!isPlainAnchor(location.hash)) return;
    // Don't yank the page out from under someone who has scrolled themselves.
    if (!force && window.scrollY > 4) return;
    document.getElementById(location.hash.replace(/^#/, "")).scrollIntoView();
  }

  function writeHashState() {
    var bits = [];
    if (!PAGE_CATEGORY && state.category !== "all") bits.push("cat-" + state.category);
    if (state.search) bits.push("q=" + encHash(state.search));
    if (state.brand !== "all") bits.push("brand=" + encHash(state.brand));
    if (state.mode !== "simple") bits.push("mode=" + state.mode);
    if (state.figure) bits.push("fig=" + encHash(state.figure));
    if (state.bucket !== "all") bits.push("range=" + state.bucket);
    if (state.dir) bits.push("sort=" + state.dir);
    if (state.price !== "all") bits.push("price=" + encHash(state.price));
    if (state.label !== "all") bits.push("label=" + state.label);
    if (state.target !== undefined) bits.push("near=" + state.target);
    if (state.tolerance) bits.push("within=" + state.tolerance);

    var hash = bits.length ? "#" + bits.join("&") : "";
    // Nothing to write and the reader followed an anchor here: leave it be,
    // or the first render strips #compare out from under them.
    if (!bits.length && isPlainAnchor(location.hash)) return;
    if (hash === location.hash) return;
    history.replaceState(null, "", location.pathname + location.search + hash);
  }

  // Legacy deep links (hub.html#p-<id>) now live at products/<id>.html.
  // Reports whether it is navigating away, so the caller can stop.
  function redirectLegacyHash() {
    var m = /^#p-([a-z0-9-]+)$/.exec(location.hash);
    if (!m || !byId(m[1])) return false;
    location.replace("products/" + m[1] + ".html");
    return true;
  }

  /* ---------------------------------------------------------------------
   * Homepage: database preview + places to start
   * ------------------------------------------------------------------- */

  var PREVIEW_IDS = [
    "ryse-godzilla", "legion-pulse", "kaged-pre-kaged",
    "transparent-labs-bulk", "c4-original", "legion-pulse-stim-free"
  ];

  function byId(id) {
    return PRODUCTS.find(function (p) { return p.id === id; });
  }

  function previewRowHTML(p) {
    return "<tr>" +
      "<td>" + productLinkCell(p) + "</td>" +
      '<td class="sc-num">' + esc(p.caffeineMg) + " mg</td>" +
      '<td class="sc-num">' + citrullineHTML(p) + "</td>" +
      '<td class="sc-num">' + betaHTML(p) + "</td>" +
      "<td>" + blendHTML(p) + "</td>" +
      "<td>" + esc(stimLabelOf(p)) + "</td>" +
    "</tr>";
  }

  function renderPreview() {
    var body = document.getElementById("sc-preview-body");
    body.innerHTML = PREVIEW_IDS.map(byId).filter(Boolean).map(previewRowHTML).join("");
  }

  // Editorial framing for the FEATURED_IDS picks; stats come from the data.
  var START_META = {
    "ryse-godzilla": {
      label: "Highest caffeine on file",
      why: "Close to the FDA's 400 mg daily reference amount in a single serving."
    },
    "transparent-labs-bulk": {
      label: "Disclosed formula at studied doses",
      why: "Citrulline, beta-alanine, and betaine all at commonly studied amounts."
    },
    "legion-pulse-stim-free": {
      label: "Stim-free option",
      why: "Pump and focus ingredients at full doses, without caffeine."
    }
  };

  function renderStarts() {
    var target = document.getElementById("sc-starts");
    target.innerHTML = FEATURED_IDS.map(function (id) {
      var p = byId(id);
      var meta = START_META[id];
      if (!p || !meta) return "";
      return '<div class="sc-start">' +
        '<p class="sc-start-label">' + esc(meta.label) + "</p>" +
        '<p class="sc-start-body"><strong>' + esc(p.brand + " " + p.name) + "</strong> · " +
          esc(p.caffeineMg) + " mg caffeine" +
          '<span class="sc-start-why">' + esc(meta.why) + "</span></p>" +
        '<a class="sc-action-link" href="products/' + esc(p.id) + '.html">Label breakdown</a>' +
      "</div>";
    }).join("");
  }

  /* ---------------------------------------------------------------------
   * Compare page — sortable full-database table
   * ------------------------------------------------------------------- */

  var compareState = { key: "name", dir: 1 };

  // Compare tables are per-category: the page's data-category picks the
  // column set from CATEGORY_CONFIG and locks the row set. The <thead> is
  // built here so category pages ship an empty table shell.
  function compareCfg() {
    return CATEGORY_CONFIG[PAGE_CATEGORY] || CATEGORY_CONFIG["pre-workout"];
  }

  function buildCompareHead() {
    var head = document.querySelector("#sc-compare thead");
    var cols = compareCfg().compareCols;
    var cells = ['<th scope="col" data-sortkey="name">' +
      '<button type="button" class="sc-sort-btn">Product</button></th>'];
    for (var i = 0; i < cols.length; i++) {
      var c = cols[i];
      cells.push('<th scope="col"' + (c.num ? ' class="sc-num"' : "") +
        (c.sortable ? ' data-sortkey="' + esc(c.key) + '"' : "") + ">" +
        (c.sortable
          ? '<button type="button" class="sc-sort-btn">' + esc(c.label) + "</button>"
          : esc(c.label)) +
      "</th>");
    }
    head.innerHTML = "<tr>" + cells.join("") + "</tr>";
  }

  function compareRowHTML(p) {
    var cols = compareCfg().compareCols;
    var cells = ["<td>" + productLinkCell(p) + "</td>"];
    for (var i = 0; i < cols.length; i++) {
      cells.push("<td" + (cols[i].num ? ' class="sc-num"' : "") + ">" +
        factOf(p, cols[i].key) + "</td>");
    }
    return "<tr>" + cells.join("") + "</tr>";
  }

  function renderCompare() {
    var body = document.getElementById("sc-compare-body");
    var rows = PRODUCTS.filter(function (p) {
      return !PAGE_CATEGORY || categoryOf(p) === PAGE_CATEGORY;
    }).sort(function (a, b) {
      var va = factSortValue(a, compareState.key);
      var vb = factSortValue(b, compareState.key);
      if (va < vb) return -1 * compareState.dir;
      if (va > vb) return 1 * compareState.dir;
      return 0;
    });
    body.innerHTML = rows.map(compareRowHTML).join("");

    syncCompareSort();

    var headers = document.querySelectorAll("#sc-compare th[data-sortkey]");
    for (var i = 0; i < headers.length; i++) {
      var key = headers[i].getAttribute("data-sortkey");
      if (key === compareState.key) {
        headers[i].setAttribute("aria-sort",
          compareState.dir === 1 ? "ascending" : "descending");
      } else {
        headers[i].removeAttribute("aria-sort");
      }
    }
  }

  /* The table sorts from its column headings, which is fine with a mouse on a
   * wide screen. On a phone the headings are off the top of the screen by the
   * time the rows are in reach, so "click a column heading to sort" was an
   * instruction with nothing on screen to follow it with. Same sort, offered
   * where the table starts. */
  function buildCompareSort() {
    var table = document.getElementById("sc-compare");
    var scroll = table && table.closest(".sc-table-scroll");
    if (!scroll || document.getElementById("sc-csort")) return;

    var cfg = CATEGORY_CONFIG[PAGE_CATEGORY || "pre-workout"] || CATEGORY_CONFIG["pre-workout"];
    var cols = [{ value: "name", label: "Product name" }].concat(
      (cfg.compareCols || []).filter(function (c) { return c.sortable; })
        .map(function (c) { return { value: c.key, label: c.label }; })
    );

    var row = document.createElement("div");
    row.className = "sc-csort-row";
    row.id = "sc-csort-row";
    row.innerHTML =
      fieldHTML("Sort by", "sc-csort", selectHTML("sc-csort", optionsHTML(cols, compareState.key))) +
      fieldHTML("Order", "sc-cdir", selectHTML("sc-cdir", ""));
    scroll.parentNode.insertBefore(row, scroll);

    row.addEventListener("change", function (event) {
      if (event.target.id === "sc-csort") {
        compareState.key = event.target.value;
        // Match the heading click: figures read high-to-low first, names A–Z.
        compareState.dir = compareState.key === "name" ? 1 : -1;
      }
      else if (event.target.id === "sc-cdir") compareState.dir = parseInt(event.target.value, 10);
      else return;
      renderCompare();
    });
  }

  /* Keeps the two selects showing what the table is actually doing, including
   * after a heading click, and words the order the way the chosen column reads
   * — names run A–Z, figures run high to low. */
  function syncCompareSort() {
    var key = document.getElementById("sc-csort");
    var dir = document.getElementById("sc-cdir");
    if (!key || !dir) return;
    key.value = compareState.key;
    var byName = compareState.key === "name";
    dir.innerHTML = optionsHTML([
      { value: "-1", label: byName ? "Z–A" : "High to low" },
      { value: "1", label: byName ? "A–Z" : "Low to high" }
    ], String(compareState.dir));
  }

  function wireCompare() {
    var head = document.querySelector("#sc-compare thead");
    buildCompareHead();
    buildCompareSort();
    head.addEventListener("click", function (event) {
      var btn = event.target.closest(".sc-sort-btn");
      if (!btn) return;
      var th = btn.closest("th[data-sortkey]");
      if (!th) return;
      var key = th.getAttribute("data-sortkey");
      if (compareState.key === key) {
        compareState.dir = -compareState.dir;
      } else {
        compareState.key = key;
        // Numbers read best high-to-low on first click; names A-Z.
        compareState.dir = key === "name" ? 1 : -1;
      }
      renderCompare();
    });
  }

  /* ---------------------------------------------------------------------
   * Structured data — ItemList of the full database (hub page only).
   * ------------------------------------------------------------------- */

  function injectCatalogLD() {
    var scoped = PRODUCTS.filter(function (p) {
      return !PAGE_CATEGORY || categoryOf(p) === PAGE_CATEGORY;
    });
    var ld = {
      "@context": "https://schema.org",
      "@type": "ItemList",
      "name": PAGE_CATEGORY && CATEGORY_CONFIG[PAGE_CATEGORY]
        ? CATEGORY_CONFIG[PAGE_CATEGORY].label + " label database"
        : "Supplement label database",
      "numberOfItems": scoped.length,
      "itemListElement": scoped.map(function (p, i) {
        return {
          "@type": "ListItem",
          "position": i + 1,
          "name": p.brand + " " + p.name,
          "url": "products/" + p.id + ".html"
        };
      })
    };
    var script = document.createElement("script");
    script.type = "application/ld+json";
    script.textContent = JSON.stringify(ld);
    document.head.appendChild(script);
  }

  /* ---------------------------------------------------------------------
   * Scroll reveal — subtle rise-in as sections enter the viewport.
   * Runs on every page (product pages load this file without data).
   * Elements are only hidden AFTER the observer exists, so no-JS and
   * old browsers always see the full page.
   * ------------------------------------------------------------------- */

  var revealObserver = null;

  // Above-the-fold blocks (hero, hub intro, PDP top, buybox) animate on
  // page load via CSS instead — never list them here or they double-fire.
  var REVEAL_TARGETS = [
    ".sc-section-head", ".sc-table-scroll", ".sc-table-note",
    ".sc-method-steps li", ".sc-annotated", ".sc-start", ".sc-faq details",
    ".sc-safety", ".sc-cta-band .sc-container", ".sc-tile", ".sc-facts",
    ".sc-related-card", ".sc-pdp-h2", ".sc-pdp-reviews-note",
    ".sc-verify-note", ".sc-footer-grid"
  ].join(", ");

  function initReveal() {
    if (!("IntersectionObserver" in window)) return;

    if (!revealObserver) {
      revealObserver = new IntersectionObserver(function (entries) {
        for (var i = 0; i < entries.length; i++) {
          if (entries[i].isIntersecting) {
            entries[i].target.classList.add("sc-in");
            revealObserver.unobserve(entries[i].target);
          }
        }
        // threshold counts a fraction of the ELEMENT, so a tall one has to
        // clear a bar that grows with it: a 5,000px compare table would need
        // 750px on screen at 0.15, more than a phone viewport minus the
        // rootMargin ever offers. It then never intersects, never gets .sc-in,
        // and stays at opacity 0 — the table is simply gone. Reveal on the
        // first pixel instead; the rootMargin still holds it until the element
        // is properly in view.
      }, { rootMargin: "0px 0px -14% 0px", threshold: 0 });
    }

    var els = document.querySelectorAll(REVEAL_TARGETS);
    for (var j = 0; j < els.length; j++) {
      if (els[j].dataset.reveal) continue;
      els[j].dataset.reveal = "1";
      els[j].classList.add("sc-reveal");
      revealObserver.observe(els[j]);
    }
  }

  /* ---------------------------------------------------------------------
   * Shortlist — "save to compare". Deliberately NOT a cart: nothing can be
   * bought on this site. It's a reading list for side-by-side label
   * comparison, stored only in the visitor's browser (localStorage).
   * Works on data-less product pages too (only needs the id).
   * ------------------------------------------------------------------- */

  var SAVE_KEY = "sc-shortlist";

  function getSaved() {
    try {
      var a = JSON.parse(localStorage.getItem(SAVE_KEY) || "[]");
      return Array.isArray(a) ? a : [];
    } catch (e) { return []; }
  }

  function storeSaved(ids) {
    try { localStorage.setItem(SAVE_KEY, JSON.stringify(ids)); } catch (e) {}
    syncSaveUI();
  }

  function toggleSaved(id) {
    var ids = getSaved();
    var i = ids.indexOf(id);
    if (i === -1) ids.push(id); else ids.splice(i, 1);
    storeSaved(ids);
  }

  function saveBtnHTML(p) {
    var saved = getSaved().indexOf(p.id) !== -1;
    var label = saved ? "Saved to compare" : "Save to compare";
    // On tiles the text is hidden by CSS, so the button needs its own name.
    return '<button type="button" class="sc-save-btn" data-save-id="' + esc(p.id) + '" ' +
      'aria-pressed="' + saved + '" aria-label="' + esc(label + ": " + p.brand + " " + p.name) + '" ' +
      'title="' + esc(label) + '">' +
      '<span class="sc-save-icon" aria-hidden="true"></span>' +
      '<span class="sc-save-text">' + (saved ? "Saved" : "Save to compare") + "</span>" +
    "</button>";
  }

  // Refresh every save toggle, nav counter, and the saved page (if open).
  function syncSaveUI() {
    var ids = getSaved();
    var btns = document.querySelectorAll("[data-save-id]");
    for (var i = 0; i < btns.length; i++) {
      var saved = ids.indexOf(btns[i].getAttribute("data-save-id")) !== -1;
      btns[i].setAttribute("aria-pressed", saved ? "true" : "false");
      var t = btns[i].querySelector(".sc-save-text");
      if (t) t.textContent = saved ? "Saved" : "Save to compare";
    }
    var counts = document.querySelectorAll(".sc-saved-count");
    for (var j = 0; j < counts.length; j++) {
      counts[j].textContent = ids.length ? "(" + ids.length + ")" : "";
    }
    var savedRoot = document.getElementById("sc-saved-root");
    if (savedRoot && typeof PRODUCTS !== "undefined") renderSavedPage(savedRoot);
  }

  function savedRowHTML(label, cells) {
    return "<tr><th scope=\"row\">" + esc(label) + "</th>" + cells.join("") + "</tr>";
  }

  function renderSavedPage(root) {
    var products = getSaved().map(byId).filter(Boolean);

    if (!products.length) {
      root.innerHTML =
        '<div class="sc-empty">' +
          "<p>Nothing saved yet. Browse the database and hit “Save to compare” on any product — it'll wait for you here.</p>" +
          '<p><a class="sc-btn sc-btn-primary" href="hub.html">Browse all products</a></p>' +
        "</div>";
      return;
    }

    var head = products.map(function (p) {
      return '<td class="sc-saved-col">' +
        // Decorative twin of the named link below it: hidden from assistive
        // tech rather than announced as a second, nameless "link".
        '<span class="sc-saved-art" aria-hidden="true">' +
          (p.imageUrl
            ? '<img src="' + esc(p.imageUrl) + '" alt="" loading="lazy" referrerpolicy="no-referrer">'
            : tubSVG(p)) +
        "</span>" +
        '<span class="sc-tile-brand">' + esc(p.brand) + "</span>" +
        '<a class="sc-saved-name" href="products/' + esc(p.id) + '.html">' + esc(p.name) + "</a>" +
        '<button type="button" class="sc-saved-remove" data-remove-id="' + esc(p.id) + '">Remove</button>' +
      "</td>";
    });

    // Saves cross categories, so metric rows come from the configs of the
    // categories actually present — a dash marks "does not apply".
    var factRows = [];
    var seenLabels = {};
    products.forEach(function (p) {
      cfgOf(p).tileFacts.forEach(function (f) {
        if (seenLabels[f.label]) return;
        seenLabels[f.label] = true;
        factRows.push(savedRowHTML(f.label, products.map(function (q) {
          return '<td class="sc-num">' + factOf(q, f.key) + "</td>";
        })));
      });
    });

    var anyStim = products.some(showsStimTag);

    var rows = [
      savedRowHTML("Category", products.map(function (p) { return "<td>" + esc(categoryLabelOf(p)) + "</td>"; }))
    ].concat(factRows, [
      savedRowHTML("Proprietary blend", products.map(function (p) { return "<td>" + blendHTML(p) + "</td>"; })),
      savedRowHTML("Servings", products.map(function (p) { return '<td class="sc-num">' + esc(p.servings) + "</td>"; })),
      savedRowHTML("Price tier", products.map(function (p) { return "<td>" + priceWordHTML(p) + "</td>"; }))
    ], anyStim ? [
      savedRowHTML("Stim tier", products.map(function (p) {
        return "<td>" + (showsStimTag(p) || categoryOf(p) === "pre-workout" ? esc(stimLabelOf(p)) : '<span class="sc-dim">—</span>') + "</td>";
      }))
    ] : [], [
      "<tr><th scope=\"row\">Links</th>" + products.map(function (p) {
        return '<td class="sc-saved-links">' +
          '<a class="sc-btn sc-btn-primary" href="products/' + esc(p.id) + '.html">Full breakdown</a>' +
          '<a class="sc-btn sc-btn-secondary" href="' + esc(p.affiliateUrl) + '" target="_blank" rel="sponsored nofollow noopener">View current price at ' + esc(retailerOf(p)) + ' <span class="sc-ext" aria-hidden="true">&#8599;</span></a>' +
        "</td>";
      }).join("") + "</tr>"
    ]);

    root.innerHTML =
      '<p class="sc-count">' + products.length + " saved · stored only in this browser</p>" +
      '<div class="sc-table-scroll sc-saved-scroll">' +
        '<table class="sc-table sc-saved-table">' +
          "<tbody><tr><td></td>" + head.join("") + "</tr>" + rows.join("") + "</tbody>" +
        "</table>" +
      "</div>" +
      '<p class="sc-verify-note">Figures come from manufacturer labels and can change without notice — always verify against the current label on the product you buy.</p>' +
      '<p><button type="button" class="sc-clear-btn" id="sc-saved-clear">Clear all saved</button></p>';
  }

  // One delegated listener covers hub tiles, product pages, and the saved page.
  document.addEventListener("click", function (e) {
    var target = e.target;
    var saveBtn = target.closest ? target.closest("[data-save-id]") : null;
    if (saveBtn) {
      e.preventDefault();
      toggleSaved(saveBtn.getAttribute("data-save-id"));
      return;
    }
    var removeBtn = target.closest ? target.closest("[data-remove-id]") : null;
    if (removeBtn) {
      toggleSaved(removeBtn.getAttribute("data-remove-id"));
      return;
    }
    if (target.id === "sc-saved-clear") storeSaved([]);
  });

  /* ---------------------------------------------------------------------
   * Init
   * ------------------------------------------------------------------- */

  /* A sticky table head has to clear the sticky toolbar on pages that have
   * one. The toolbar's height changes when its controls wrap, so measure it
   * rather than hard-coding an offset. */
  function syncStickyOffsets() {
    var toolbar = document.querySelector(".sc-toolbar");
    if (!toolbar) return;
    var set = function () {
      document.body.style.setProperty(
        "--sc-table-head-top", Math.round(toolbar.getBoundingClientRect().height) + "px"
      );
    };
    set();
    if (window.ResizeObserver) new ResizeObserver(set).observe(toolbar);
    else window.addEventListener("resize", set);
  }

  /* The browse pages left their whole top-right quadrant empty while the
   * homepage filled it with the facts panel. Same device here, scoped to
   * whatever the page is actually showing — counts come from the data, so
   * they cannot drift out of date the way hand-written figures do. */
  function renderIntroPanel() {
    var panel = document.getElementById("sc-intropanel");
    if (!panel || typeof PRODUCTS === "undefined") return;

    var scope = PAGE_CATEGORY
      ? PRODUCTS.filter(function (p) { return categoryOf(p) === PAGE_CATEGORY; })
      : PRODUCTS;
    if (!scope.length) return;

    var cfg = PAGE_CATEGORY ? CATEGORY_CONFIG[PAGE_CATEGORY] : null;
    var disclosed = scope.filter(isDisclosed).length;
    var blends = scope.filter(hasBlend).length;
    var tested = scope.filter(function (p) {
      return p.badges.indexOf("Third-Party Tested") !== -1;
    }).length;

    var rows = [
      ["Labels on file", scope.length],
      ["Fully disclosed", disclosed + " of " + scope.length],
      ["Proprietary blends", blends + " of " + scope.length],
      ["Third-party tested", tested + " of " + scope.length]
    ];

    if (!PAGE_CATEGORY || (cfg && cfg.stimBadges)) {
      var caf = scope.map(function (p) { return p.caffeineMg; });
      rows.splice(1, 0, ["Caffeine range", Math.min.apply(null, caf) + "–" + Math.max.apply(null, caf) + " mg"]);
    }

    panel.innerHTML =
      '<p class="sc-intropanel-title">' + esc(cfg ? cfg.label + " facts" : "Database facts") + "</p>" +
      "<dl>" + rows.map(function (r) {
        return "<div><dt>" + esc(r[0]) + "</dt><dd>" + esc(r[1]) + "</dd></div>";
      }).join("") + "</dl>" +
      '<p class="sc-intropanel-note">Every figure is counted from the labels on file, checked July 2026.</p>';
    panel.hidden = false;
  }

  /* Homepage figures used to be typed into index.html by hand, so every data
   * change silently aged them. They are counted from PRODUCTS now: any
   * element carrying data-stat gets filled, and each category card's count
   * comes from the catalog. */
  function renderHomeStats() {
    if (typeof PRODUCTS === "undefined") return;

    var pre = PRODUCTS.filter(function (p) { return categoryOf(p) === "pre-workout"; });
    var caf = pre.map(function (p) { return p.caffeineMg; });
    var stats = {
      total: PRODUCTS.length,
      categories: Object.keys(CATEGORY_CONFIG).length,
      disclosed: PRODUCTS.filter(isDisclosed).length + " of " + PRODUCTS.length,
      blends: PRODUCTS.filter(hasBlend).length + " of " + PRODUCTS.length,
      tested: PRODUCTS.filter(function (p) {
        return p.badges.indexOf("Third-Party Tested") !== -1;
      }).length + " of " + PRODUCTS.length,
      cafRange: caf.length ? Math.min.apply(null, caf) + "–" + Math.max.apply(null, caf) + " mg" : "—",
      preCount: pre.length,
      totalLabels: PRODUCTS.length + " supplement labels on file"
    };

    var nodes = document.querySelectorAll("[data-stat]");
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute("data-stat");
      if (stats[key] !== undefined) nodes[i].textContent = stats[key];
    }

    var cards = document.querySelectorAll("[data-cat-count]");
    for (var j = 0; j < cards.length; j++) {
      var slug = cards[j].getAttribute("data-cat-count");
      var n = PRODUCTS.filter(function (p) { return categoryOf(p) === slug; }).length;
      cards[j].textContent = n + (n === 1 ? " label" : " labels");
    }
  }

  function init() {
    syncSaveUI(); // nav counter + save toggles work on every page
    syncStickyOffsets();
    renderIntroPanel();
    renderHomeStats();

    if (typeof PRODUCTS === "undefined") {
      initReveal(); // product pages: motion only, no data renderers
      return;
    }

    var hub = document.getElementById("sc-products");
    var preview = document.getElementById("sc-preview-body");
    var starts = document.getElementById("sc-starts");
    var compare = document.getElementById("sc-compare-body");

    if (hub) {
      // First, before the filter reads or rewrites the hash: a #p-<id> link
      // is a navigation, not filter state, and the rewrite would eat it.
      if (redirectLegacyHash()) return;
      wireFilters();
      renderHub();
      injectCatalogLD();
    }

    if (preview) renderPreview();
    if (starts) renderStarts();

    if (compare) {
      wireCompare();
      renderCompare();
    }

    initReveal();

    // Last: the anchor the browser tried to reach before any of these
    // renderers had put anything on the page. See jumpToAnchor.
    jumpToAnchor();
  }

  document.addEventListener("DOMContentLoaded", init);
})();
